presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-kops-aws
    skip_branches:
    - release-\d+\.\d+
    annotations:
      fork-per-release: "true"
      testgrid-alert-stale-results-hours: "24"
      testgrid-create-test-group: "true"
      testgrid-num-failures-to-alert: "10"
    max_concurrency: 12
    always_run: false
    optional: true
    labels:
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
      preset-e2e-platform-aws: "true"
      preset-dind-enabled: "true"
    decorate: true
    decoration_config:
      timeout: 75m
    path_alias: k8s.io/kubernetes
    extra_refs:
    - org: kubernetes
      repo: release
      base_ref: master
      path_alias: k8s.io/release
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231015-d38ebb23ab-master
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --aws
        - --aws-cluster-domain=test-cncf-aws.k8s.io
        - --build=quick
        - --cluster=
        - --kops-ssh-user=ubuntu
        - --env=KOPS_ARCH=amd64
        - --env=KOPS_RUN_TOO_NEW_VERSION=1
        - --env=KOPS_LATEST=latest-ci-green.txt
        - --env=KOPS_DEPLOY_LATEST_KUBE=n
        - --env=KUBE_GCS_UPDATE_LATEST=n
        - --env=KUBE_FASTBUILD=true
        - --env=USER=ubuntu
        - --extract=local
        - --ginkgo-parallel
        - --provider=aws
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-kops-aws
        - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]
        - --timeout=55m
        resources:
          requests:
            memory: "6Gi"
        securityContext:
          privileged: true
