#
# Define test groups
#
test_groups:
- name: gcp-guest-osconfig-presubmit-gobuild
  gcs_prefix: oss-prow/pr-logs/directory/osconfig-presubmit-gobuild
- name: gcp-guest-osconfig-presubmit-gotest
  gcs_prefix: oss-prow/pr-logs/directory/osconfig-presubmit-gotest
- name: gcp-guest-osconfig-presubmit-gocheck
  gcs_prefix: oss-prow/pr-logs/directory/osconfig-presubmit-gocheck
- name: cit-periodics
  gcs_prefix: oss-prow/logs/cit-periodics
- name: oslogin-periodics
  gcs_prefix: oss-prow/logs/oslogin-periodics

#
# Define dashboards
#
dashboards:
- name: google-gcp-guest
  dashboard_tab:
  - name: OSConfig presubmits - gobuild
    test_group_name: gcp-guest-osconfig-presubmit-gobuild
  - name: OSConfig presubmits - gotest
    test_group_name: gcp-guest-osconfig-presubmit-gotest
  - name: OSConfig presubmits - gocheck
    test_group_name: gcp-guest-osconfig-presubmit-gocheck
  - name: CIT periodics
    test_group_name: cit-periodics
    alert_options:
      alert_mail_to_addresses: 'buganizer-system+117405@google.com'
      debug_url: 'http://go/cit-alert-runbook'
  - name: OSLogin periodics
    test_group_name: oslogin-periodics
    alert_options:
      alert_mail_to_addresses: 'buganizer-system+117405@google.com'
      debug_url: 'http://go/cit-alert-runbook'

