periodics:
  - interval: 12h
    name: periodic-kueue-test-unit-main
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-unit-main
      testgrid-alert-email: kueue-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic kueue unit tests"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: public.ecr.aws/docker/library/golang:1.21
          env:
            - name: GO_TEST_FLAGS
              value: "-race -count 3"
            - name: GOMAXPROCS
              value: "2"
          command:
            - make
          args:
            - test
          resources:
            requests:
              cpu: "2"
              memory: "6Gi"
            limits:
              cpu: "2"
              memory: "6Gi"
  - interval: 12h
    name: periodic-kueue-test-integration-main
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-integration-main
      testgrid-alert-email: kueue-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic kueue test-integration"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: public.ecr.aws/docker/library/golang:1.21
          command:
            - make
          args:
            - test-integration
          env:
            - name: GOMAXPROCS
              value: "4"
          resources:
            requests:
              cpu: "4"
              memory: "6Gi"
            limits:
              cpu: "4"
              memory: "6Gi"
  - interval: 12h
    name: periodic-kueue-test-e2e-main-1-25
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-e2e-main-1-25
      testgrid-alert-email: kueue-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic kueue end to end tests for Kubernetes 1.25"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
          env:
            - name: E2E_KIND_VERSION
              value: kindest/node:v1.25.11
            - name: BUILDER_IMAGE
              value: public.ecr.aws/docker/library/golang:1.21
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - kind-image-build
            - test-e2e
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "10"
              memory: "10Gi"
            limits:
              cpu: "10"
              memory: "10Gi"
  - interval: 12h
    name: periodic-kueue-test-e2e-main-1-26
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-e2e-main-1-26
      testgrid-alert-email: kueue-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic kueue end to end tests for Kubernetes 1.26"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
          env:
            - name: E2E_KIND_VERSION
              value: kindest/node:v1.26.6
            - name: BUILDER_IMAGE
              value: public.ecr.aws/docker/library/golang:1.21
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - kind-image-build
            - test-e2e
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "10"
              memory: "10Gi"
            limits:
              cpu: "10"
              memory: "10Gi"
  - interval: 12h
    name: periodic-kueue-test-e2e-main-1-27
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-e2e-main-1-27
      testgrid-alert-email: kueue-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic kueue end to end tests for Kubernetes 1.27"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
          env:
            - name: E2E_KIND_VERSION
              value: kindest/node:v1.27.3
            - name: BUILDER_IMAGE
              value: public.ecr.aws/docker/library/golang:1.21
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - kind-image-build
            - test-e2e
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "10"
              memory: "10Gi"
            limits:
              cpu: "10"
              memory: "10Gi"
  - interval: 12h
    name: periodic-kueue-test-e2e-main-1-28
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-e2e-main-1-28
      testgrid-alert-email: kueue-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic kueue end to end tests for Kubernetes 1.28"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
          env:
            - name: E2E_KIND_VERSION
              value: kindest/node:v1.28.0
            - name: BUILDER_IMAGE
              value: public.ecr.aws/docker/library/golang:1.21
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - kind-image-build
            - test-e2e
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "10"
              memory: "10Gi"
            limits:
              cpu: "10"
              memory: "10Gi"
  - interval: 12h
    name: periodic-kueue-test-e2e-main-1-29
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-e2e-main-1-29
      testgrid-alert-email: kueue-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
      description: "Run periodic kueue end to end tests for Kubernetes 1.29"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
          env:
            - name: E2E_KIND_VERSION
              value: kindest/node:v1.29.0
            - name: BUILDER_IMAGE
              value: public.ecr.aws/docker/library/golang:1.21
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - kind-image-build
            - test-e2e
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "10"
              memory: "10Gi"
            limits:
              cpu: "10"
              memory: "10Gi"
