periodics:
  - interval: 12h
    name: periodic-kueue-test-unit-main
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-unit-main
      description: "Run periodic kueue unit tests"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: golang:1.20
          env:
            - name: GO_TEST_FLAGS
              value: "-race -count 3"
          command:
            - make
          args:
            - test
  - interval: 12h
    name: periodic-kueue-test-integration-main
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-integration-main
      description: "Run periodic kueue test-integration"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: golang:1.20
          command:
            - make
          args:
            - test-integration
  - interval: 12h
    name: periodic-kueue-test-e2e-main-1-24
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-e2e-main-1-24
      description: "Run periodic kueue end to end tests for Kubernetes 1.24"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230406-23cb1879e3-master
          env:
            - name: E2E_KIND_VERSION
              value: kindest/node:v1.24.7
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - kind-image-build
            - test-e2e
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
  - interval: 12h
    name: periodic-kueue-test-e2e-main-1-25
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-e2e-main-1-25
      description: "Run periodic kueue end to end tests for Kubernetes 1.25"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230406-23cb1879e3-master
          env:
            - name: E2E_KIND_VERSION
              value: kindest/node:v1.25.3
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - kind-image-build
            - test-e2e
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
  - interval: 12h
    name: periodic-kueue-test-e2e-main-1-26
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-test-e2e-main-1-26
      description: "Run periodic kueue end to end tests for Kubernetes 1.26"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230406-23cb1879e3-master
          env:
            - name: E2E_KIND_VERSION
              value: kindest/node:v1.26.2
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - kind-image-build
            - test-e2e
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
  - interval: 12h
    name: periodic-kueue-verify-main
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: periodic-kueue-verify-main
      description: "Run periodic kueue verify checks"
      testgrid-num-columns-recent: '30'
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
      - org: kubernetes-sigs
        repo: kueue
        base_ref: main
        path_alias: kubernetes-sigs/kueue
    decorate: true
    decoration_config:
      timeout: 1h
    spec:
      containers:
        - image: golang:1.20
          command:
            - make
          args:
            - verify
