presubmits:
  kubernetes-sigs/kueue:
  - name: pull-kueue-test-unit-release-0-5
    cluster: eks-prow-build-cluster
    branches:
    - ^release-0.5
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-test-unit-release-0-5
      description: "Run kueue unit tests"
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.21
        env:
        - name: GO_TEST_FLAGS
          value: "-race -count 3"
        - name: GOMAXPROCS
          value: "2"
        command:
        - make
        args:
        - test
        resources:
          requests:
            cpu: "2"
            memory: "6Gi"
          limits:
            cpu: "2"
            memory: "6Gi"
  - name: pull-kueue-test-integration-release-0-5
    cluster: eks-prow-build-cluster
    branches:
    - ^release-0.5
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-test-integration-release-0-5
      description: "Run kueue test-integration"
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.21
        command:
        - make
        args:
        - test-integration
        env:
        - name: GOMAXPROCS
          value: "4"
        resources:
          requests:
            cpu: "4"
            memory: "6Gi"
          limits:
            cpu: "4"
            memory: "6Gi"
  - name: pull-kueue-test-e2e-release-0-5-1-25
    cluster: eks-prow-build-cluster
    branches:
    - ^release-0.5
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-test-e2e-release-0-5-1-25
      description: "Run kueue end to end tests for Kubernetes 1.25"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        env:
        - name: E2E_KIND_VERSION
          value: kindest/node:v1.25.11
        - name: BUILDER_IMAGE
          value: public.ecr.aws/docker/library/golang:1.21
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - kind-image-build
        - test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "10"
            memory: "10Gi"
          limits:
            cpu: "10"
            memory: "10Gi"
  - name: pull-kueue-test-e2e-release-0-5-1-26
    cluster: eks-prow-build-cluster
    branches:
    - ^release-0.5
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-test-e2e-release-0-5-1-26
      description: "Run kueue end to end tests for Kubernetes 1.26"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        env:
        - name: E2E_KIND_VERSION
          value: kindest/node:v1.26.6
        - name: BUILDER_IMAGE
          value: public.ecr.aws/docker/library/golang:1.21
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - kind-image-build
        - test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "10"
            memory: "10Gi"
          limits:
            cpu: "10"
            memory: "10Gi"
  - name: pull-kueue-test-e2e-release-0-5-1-27
    cluster: eks-prow-build-cluster
    branches:
    - ^release-0.5
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-test-e2e-release-0-5-1-27
      description: "Run kueue end to end tests for Kubernetes 1.27"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        env:
        - name: E2E_KIND_VERSION
          value: kindest/node:v1.27.3
        - name: BUILDER_IMAGE
          value: public.ecr.aws/docker/library/golang:1.21
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - kind-image-build
        - test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "10"
            memory: "10Gi"
          limits:
            cpu: "10"
            memory: "10Gi"
  - name: pull-kueue-test-e2e-release-0-5-1-28
    cluster: eks-prow-build-cluster
    branches:
      - ^release-0.5
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-test-e2e-release-0-5-1-28
      description: "Run kueue end to end tests for Kubernetes 1.28"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
          env:
            - name: E2E_KIND_VERSION
              value: kindest/node:v1.28.0
            - name: BUILDER_IMAGE
              value: public.ecr.aws/docker/library/golang:1.21
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - kind-image-build
            - test-e2e
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "10"
              memory: "10Gi"
            limits:
              cpu: "10"
              memory: "10Gi"
  - name: pull-kueue-test-e2e-release-0-5-1-29
    cluster: eks-prow-build-cluster
    branches:
      - ^release-0.5
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-test-e2e-release-0-5-1-29
      description: "Run kueue end to end tests for Kubernetes 1.29"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
          env:
            - name: E2E_KIND_VERSION
              value: kindest/node:v1.29.0
            - name: BUILDER_IMAGE
              value: public.ecr.aws/docker/library/golang:1.21
          command:
            # generic runner script, handles DIND, bazelrc for caching, etc.
            - runner.sh
          args:
            - make
            - kind-image-build
            - test-e2e
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: "10"
              memory: "10Gi"
            limits:
              cpu: "10"
              memory: "10Gi"
  - name: pull-kueue-verify-release-0-5
    cluster: eks-prow-build-cluster
    branches:
    - ^release-0.5
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-verify-release-0-5
      description: "Run kueue verify checks"
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.21
        command:
        - make
        args:
        - verify
        env:
        - name: GOMAXPROCS
          value: "2"
        resources:
          requests:
            cpu: "2"
            memory: "6Gi"
          limits:
            cpu: "2"
            memory: "6Gi"
  - name: pull-kueue-build-image-release-0-5
    cluster: eks-prow-build-cluster
    branches:
    - ^release-0.5
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/kueue
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kueue-build-image-release-0-5
      description: "Build container image of kueue"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        securityContext:
          privileged: true
        command:
        - runner.sh
        args:
        - make
        - image-local-build
        env:
        - name: GOMAXPROCS
          value: "2"
        - name: BUILDER_IMAGE
          value: public.ecr.aws/docker/library/golang:1.21
        resources:
          requests:
            cpu: "2"
            memory: "6Gi"
          limits:
            cpu: "2"
            memory: "6Gi"
