presubmits:
  kubernetes-sigs/jobset:
  - name: pull-jobset-test-unit-release-0-4
    cluster: eks-prow-build-cluster
    branches:
    - ^release-0.4
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/jobset
    annotations:
      testgrid-dashboards: sig-apps
      testgrid-tab-name: pull-jobset-test-unit-release-0-4
      description: "Run jobset unit tests"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240515-17c6d50e24-master
        env:
        - name: GO_TEST_FLAGS
          value: "-race -count 3"
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - test
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 3
            memory: 10Gi
          requests:
            cpu: 3
            memory: 10Gi
  - name: pull-jobset-test-integration-release-0-4
    cluster: eks-prow-build-cluster
    branches:
    - ^release-0.4
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/jobset
    annotations:
      testgrid-dashboards: sig-apps
      testgrid-tab-name: pull-jobset-test-integration-release-0-4
      description: "Run jobset integration tests"
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.22
        command:
        - make
        args:
        - test-integration
        resources:
          limits:
            cpu: 3
            memory: 10Gi
          requests:
            cpu: 3
            memory: 10Gi
  - name: pull-jobset-test-e2e-release-0-4-1-27
    cluster: eks-prow-build-cluster
    branches:
    - ^release-0.4
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/jobset
    annotations:
      testgrid-dashboards: sig-apps
      estgrid-tab-name: pull-jobset-test-e2e-release-0-4-1-27
      description: "Run jobset end to end tests for Kubernetes 1.27"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240515-17c6d50e24-master
        env:
        - name: E2E_KIND_VERSION
          value: kindest/node:v1.27.3
        - name: BUILDER_IMAGE
          value: public.ecr.aws/docker/library/golang:1.21
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - test-e2e-kind
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "10"
            memory: "10Gi"
          limits:
            cpu: "10"
            memory: "10Gi"
  - name: pull-jobset-test-e2e-release-0-4-1-28
    cluster: eks-prow-build-cluster
    branches:
    - ^release-0.4
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/jobset
    annotations:
      testgrid-dashboards: sig-apps
      estgrid-tab-name: pull-jobset-test-e2e-release-0-4-1-28
      description: "Run jobset end to end tests for Kubernetes 1.28"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240515-17c6d50e24-master
        env:
        - name: E2E_KIND_VERSION
          value: kindest/node:v1.28.0
        - name: BUILDER_IMAGE
          value: public.ecr.aws/docker/library/golang:1.22
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - test-e2e-kind
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 3
            memory: 10Gi
          requests:
            cpu: 3
            memory: 10Gi
  - name: pull-jobset-test-e2e-release-0-4-1-29
    cluster: eks-prow-build-cluster
    branches:
    - ^release-0.4
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    decorate: true
    path_alias: sigs.k8s.io/jobset
    annotations:
      testgrid-dashboards: sig-apps
      testgrid-tab-name: pull-jobset-test-e2e-release-0-4-1-29
      description: "Run jobset end to end tests for Kubernetes 1.29"
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240515-17c6d50e24-master
        env:
        - name: E2E_KIND_VERSION
          value: kindest/node:v1.29.0
        - name: BUILDER_IMAGE
          value: public.ecr.aws/docker/library/golang:1.22

        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        args:
        - make
        - test-e2e-kind
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 3
            memory: 10Gi
          requests:
            cpu: 3
            memory: 10Gi
