periodics:
- name: ci-k8sio-groups
  interval: 6h
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  max_concurrency: 1
  extra_refs:
  - org: kubernetes
    repo: k8s.io
    base_ref: main
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: sig-k8s-infra-groups
    testgrid-alert-email: k8s-infra-alerts@kubernetes.io
    testgrid-num-failures-to-alert: '1'
  rerun_auth_config:
    github_team_slugs:
    # proxy for sig-k8s-infra-oncall
    - org: kubernetes
      slug: sig-k8s-infra-leads
    # team specifically for this service
    - org: kubernetes
      slug: k8s-infra-group-admins
  spec:
    serviceAccountName: gsuite-groups-manager
    containers:
    - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
      command:
      - make
      args:
      - -C
      - groups
      - run
      - --
      - --confirm

postsubmits:
  kubernetes/k8s.io:
  - name: post-k8sio-groups
    cluster: k8s-infra-prow-build-trusted
    decorate: true
    max_concurrency: 1
    run_if_changed: '^groups/'
    branches:
    - ^main$
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: sig-k8s-infra-groups
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
    rerun_auth_config:
      github_team_slugs:
      # proxy for sig-k8s-infra-oncall
      - org: kubernetes
        slug: sig-k8s-infra-leads
      # team specifically for this service
      - org: kubernetes
        slug: k8s-infra-group-admins
    spec:
      serviceAccountName: gsuite-groups-manager
      containers:
      - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
        command:
        - make
        args:
        - -C
        - groups
        - run
        - --
        - --confirm
