presubmits:
  kubernetes-sigs/downloadkubernetes:
    - name: pull-downloadkubernetes-verify-index
      always_run: true
      optional: false
      decorate: true
      path_alias: "sigs.k8s.io/downloadkubernetes"
      cluster: eks-prow-build-cluster
      spec:
        containers:
          - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.20-bookworm
            imagePullPolicy: Always
            command:
              - make
              - verify-index
            resources:
              limits:
                cpu: 2
                memory: 4Gi
              requests:
                cpu: 2
                memory: 4Gi
      annotations:
        testgrid-dashboards: sig-release-releng-presubmits
        testgrid-alert-email: release-managers+alerts@kubernetes.io

    - name: pull-downloadkubernetes-verify
      always_run: true
      optional: false
      decorate: true
      path_alias: "sigs.k8s.io/downloadkubernetes"
      cluster: eks-prow-build-cluster
      spec:
        containers:
          - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.20-bookworm
            imagePullPolicy: Always
            command:
              - make
              - verify
            resources:
              limits:
                cpu: 2
                memory: 4Gi
              requests:
                cpu: 2
                memory: 4Gi
      annotations:
        testgrid-dashboards: sig-release-releng-presubmits
        testgrid-alert-email: release-managers+alerts@kubernetes.io
