dashboards:
- dashboard_tab:
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-osd-aws-rhods-addon-baseline-fips
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-osd-aws-rhods-addon-baseline-fips
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-osd-gcp-rhods-addon-baseline-fips
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-osd-gcp-rhods-addon-baseline-fips
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-rosa-rhods-addon-baseline-fips
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-rosa-rhods-addon-baseline-fips
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-aws-rhods-addon-baseline-fips
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-aws-rhods-addon-baseline-fips
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-gcp-rhods-addon-baseline-fips
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-gcp-rhods-addon-baseline-fips
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-rosa-rhods-addon-baseline-fips
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-rosa-rhods-addon-baseline-fips
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-osd-aws-rhods-addon-baseline-fips
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-osd-aws-rhods-addon-baseline-fips
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-osd-gcp-rhods-addon-baseline-fips
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-osd-gcp-rhods-addon-baseline-fips
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-rosa-rhods-addon-baseline-fips
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-rosa-rhods-addon-baseline-fips
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-production-co-exist-rosa-rhods-rhoam
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-production-co-exist-rosa-rhods-rhoam
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam
  name: redhat-openshift-CSPI-QE-MSI-release-4.13-informing
test_groups:
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-osd-aws-rhods-addon-baseline-fips
  name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-osd-aws-rhods-addon-baseline-fips
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-osd-gcp-rhods-addon-baseline-fips
  name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-osd-gcp-rhods-addon-baseline-fips
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-rosa-rhods-addon-baseline-fips
  name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-production-smoke-rosa-rhods-addon-baseline-fips
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-aws-rhods-addon-baseline-fips
  name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-aws-rhods-addon-baseline-fips
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-gcp-rhods-addon-baseline-fips
  name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-osd-gcp-rhods-addon-baseline-fips
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-rosa-rhods-addon-baseline-fips
  name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-GA-stage-smoke-rosa-rhods-addon-baseline-fips
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-osd-aws-rhods-addon-baseline-fips
  name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-osd-aws-rhods-addon-baseline-fips
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-osd-gcp-rhods-addon-baseline-fips
  name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-osd-gcp-rhods-addon-baseline-fips
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-rosa-rhods-addon-baseline-fips
  name: periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-rosa-rhods-addon-baseline-fips
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-production-co-exist-rosa-rhods-rhoam
  name: periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-production-co-exist-rosa-rhods-rhoam
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam
  name: periodic-ci-CSPI-QE-MSI-rhods-rhoam-v4.13-stage-co-exist-rosa-rhods-rhoam
