dashboards:
- dashboard_tab:
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-multicluster-aws-4-14-nightly-hypershift-4-14-candidate-smoke
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-multicluster-aws-4-14-nightly-hypershift-4-14-candidate-smoke
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-openshift-ci-trigger-poc-test-fail-setup
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-openshift-ci-trigger-poc-test-fail-setup
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-openshift-ci-trigger-poc-test-fail-test
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-openshift-ci-trigger-poc-test-fail-test
  name: redhat-openshift-CSPI-QE-MSI-release-4.14-informing
test_groups:
- gcs_prefix: test-platform-results/logs/periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-multicluster-aws-4-14-nightly-hypershift-4-14-candidate-smoke
  name: periodic-ci-CSPI-QE-MSI-multi-cluster-smoke-v4.14-multicluster-aws-4-14-nightly-hypershift-4-14-candidate-smoke
- gcs_prefix: test-platform-results/logs/periodic-ci-CSPI-QE-MSI-openshift-ci-trigger-poc-test-fail-setup
  name: periodic-ci-CSPI-QE-MSI-openshift-ci-trigger-poc-test-fail-setup
- gcs_prefix: test-platform-results/logs/periodic-ci-CSPI-QE-MSI-openshift-ci-trigger-poc-test-fail-test
  name: periodic-ci-CSPI-QE-MSI-openshift-ci-trigger-poc-test-fail-test
