dashboards:
- dashboard_tab:
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-3scale-qe-3scale-deploy-main-3scale-amp-ocp4.13-lp-interop-3scale-amp-interop-aws
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-3scale-qe-3scale-deploy-main-3scale-amp-ocp4.13-lp-interop-3scale-amp-interop-aws
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-redhat-developer-odo-main-odo-ocp4.13-lp-interop-odo-scenario-aws
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-redhat-developer-odo-main-odo-ocp4.13-lp-interop-odo-scenario-aws
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.13-acceptance-lp-interop
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.13-acceptance-lp-interop
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance-lp-interop
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance-lp-interop
  name: redhat-openshift-lp-interop-release-4.13-informing
test_groups:
- gcs_prefix: origin-ci-test/logs/periodic-ci-3scale-qe-3scale-deploy-main-3scale-amp-ocp4.13-lp-interop-3scale-amp-interop-aws
  name: periodic-ci-3scale-qe-3scale-deploy-main-3scale-amp-ocp4.13-lp-interop-3scale-amp-interop-aws
- gcs_prefix: origin-ci-test/logs/periodic-ci-redhat-developer-odo-main-odo-ocp4.13-lp-interop-odo-scenario-aws
  name: periodic-ci-redhat-developer-odo-main-odo-ocp4.13-lp-interop-odo-scenario-aws
- gcs_prefix: origin-ci-test/logs/periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.13-acceptance-lp-interop
  name: periodic-ci-redhat-developer-service-binding-operator-release-v1.3.x-4.13-acceptance-lp-interop
- gcs_prefix: origin-ci-test/logs/periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance-lp-interop
  name: periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.13-acceptance-lp-interop
