images:
  ubuntu:
    image_family: pipeline-1-24
    project: ubuntu-os-gke-cloud
    machine: n1-standard-16  # node performance tests will be skipped on smaller machines
    metadata: "user-data</home/prow/go/src/github.com/containerd/containerd/test/e2e_node/init.yaml,containerd-configure-sh</home/prow/go/src/github.com/containerd/containerd/cluster/gce/configure.sh,containerd-env</home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/containerd-main/env"
  cos-stable:
    image_family: cos-beta
    project: cos-cloud
    machine: n1-standard-16 # node performance tests will be skipped on smaller machines
    metadata: "user-data</home/prow/go/src/github.com/containerd/containerd/test/e2e_node/init.yaml,containerd-configure-sh</home/prow/go/src/github.com/containerd/containerd/cluster/gce/configure.sh,containerd-extra-init-sh</home/prow/go/src/github.com/containerd/containerd/test/e2e_node/gci-init.sh,containerd-env</home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/containerd-main/env,gci-update-strategy=update_disabled"

# The only difference of this file from the image-config.yaml supposed to be the machine size
