presubmits:
  kubernetes-sigs/bom:
  - name: pull-bom-test
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/bom"
    cluster: eks-prow-build-cluster
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.21-bookworm
        imagePullPolicy: Always
        command:
        - go
        args:
        - run
        - mage.go
        - Test
        resources:
          requests:
            cpu: 2
            memory: 2Gi
          limits:
            cpu: 2
            memory: 2Gi
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: bom-test
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
  - name: pull-bom-verify
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/bom"
    cluster: eks-prow-build-cluster
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.21-bookworm
        imagePullPolicy: Always
        command:
        - go
        args:
        - run
        - mage.go
        - Verify
        resources:
          requests:
            cpu: 2
            memory: 2Gi
          limits:
            cpu: 2
            memory: 2Gi
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: bom-verify
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
  - name: pull-bom-check-embedded-data
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/bom"
    cluster: eks-prow-build-cluster
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.21-bookworm
        imagePullPolicy: Always
        command:
        - go
        args:
        - run
        - mage.go
        - CheckEmbeddedData
        resources:
          requests:
            cpu: 2
            memory: 2Gi
          limits:
            cpu: 2
            memory: 2Gi
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: bom-check-embedded-data
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
