steps:
  - name: gcr.io/k8s-testimages/gcb-docker-gcloud
    entrypoint: /buildx-entrypoint
    args:
    - build
    - --tag=gcr.io/$PROJECT_ID/git-custom-k8s-auth:$_GIT_TAG
    - --build-arg=IMAGE_ARG=gcr.io/$PROJECT_ID/git-custom-k8s-auth:$_GIT_TAG
    - --build-arg=AWS_IAM_AUTHENTICATOR_VERSION=$_AWS_IAM_AUTHENTICATOR_VERSION
    - --platform=linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
    - --push
    - .
    dir: .
  - name: gcr.io/k8s-testimages/gcb-docker-gcloud
    entrypoint: gcloud
    args:
    - container
    - images
    - add-tag
    - gcr.io/$PROJECT_ID/git-custom-k8s-auth:$_GIT_TAG
    - gcr.io/$PROJECT_ID/git-custom-k8s-auth:latest
substitutions:
  _GIT_TAG: '12345'
  _AWS_IAM_AUTHENTICATOR_VERSION: '0.5.12'
