periodics:
  # This jobs runs e2e.test with a focus on tests for the Dynamic Resource Allocation feature (currently alpha)
  # on a kind cluster with containerd updated to a version with CDI support.
  - name: ci-kind-dra
    cluster: eks-prow-build-cluster
    interval: 6h
    annotations:
      testgrid-dashboards: sig-node-dynamic-resource-allocation
      testgrid-tab-name: ci-kind-dra
      testgrid-alert-email: patrick.ohly@intel.com
    decorate: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        command:
        - runner.sh
        args:
        - /bin/sh
        - -xc
        - >
          make WHAT="github.com/onsi/ginkgo/v2/ginkgo k8s.io/kubernetes/test/e2e/e2e.test" &&
          curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" kind &&
          kind build node-image --image=dra/node:latest . &&
          trap 'kind export logs "${ARTIFACTS}/kind"; kind delete cluster' EXIT &&
          kind create cluster --retain --config test/e2e/dra/kind.yaml --image dra/node:latest &&
          KUBERNETES_PROVIDER=local KUBECONFIG=${HOME}/.kube/config GINKGO_PARALLEL_NODES=8 E2E_REPORT_DIR=${ARTIFACTS} hack/ginkgo-e2e.sh -ginkgo.focus=DynamicResourceAllocation -ginkgo.skip=\[Serial\]

        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 2
            memory: 9Gi
          requests:
            cpu: 2
            memory: 9Gi

  # This job runs e2e_node.test with a focus on tests for the Dynamic Resource Allocation feature (currently alpha)
  - name: ci-node-e2e-crio-dra
    cluster: k8s-infra-prow-build
    interval: 6h
    annotations:
      testgrid-dashboards: sig-node-cri-o, sig-node-dynamic-resource-allocation
      testgrid-tab-name: ci-node-e2e-crio-dra
      testgrid-alert-email: eduard.bartosh@intel.com
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    decorate: true
    decoration_config:
      timeout: 90m
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --deployment=node
        - --env=KUBE_SSH_USER=core
        - --gcp-zone=us-west1-b
        - '--node-test-args=--feature-gates="DynamicResourceAllocation=true" --service-feature-gates="DynamicResourceAllocation=true" --runtime-config=resource.k8s.io/v1alpha2=true --container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
        - --node-tests=true
        - --provider=gce
        - --test_args=--focus="\[Feature:DynamicResourceAllocation\]" --skip="\[Flaky\]"
        - --timeout=65m
        - --node-args=--image-config-file=/home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/crio/latest/image-config-cgrpv1-serial.yaml
        env:
        - name: IGNITION_INJECT_GCE_SSH_PUBLIC_KEY_FILE
          value: "1"
        - name: GOPATH
          value: /go
        resources:
          limits:
            cpu: 2
            memory: 9Gi
          requests:
            cpu: 2
            memory: 9Gi

  # This job runs the same tests as ci-node-e2e-crio-dra with Containerd 1.7 runtime
  - name: ci-node-e2e-containerd-1-7-dra
    interval: 6h
    annotations:
      testgrid-dashboards: sig-node-dynamic-resource-allocation
      testgrid-tab-name: ci-node-e2e-containerd-1-7-dra
      testgrid-alert-email: eduard.bartosh@intel.com
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    decorate: true
    decoration_config:
      timeout: 90m
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --deployment=node
        - --gcp-project-type=node-e2e-project
        - --gcp-zone=us-west1-b
        - '--node-test-args=--feature-gates="DynamicResourceAllocation=true" --service-feature-gates="DynamicResourceAllocation=true" --runtime-config=resource.k8s.io/v1alpha2=true --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock --container-runtime-process-name=/usr/local/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd\"]}"'
        - --node-tests=true
        - --provider=gce
        - --test_args=--focus="\[Feature:DynamicResourceAllocation\]" --skip="\[Flaky\]"
        - --timeout=65m
        - --node-args=--image-config-file=/home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/dra/image-config-containerd-1.7.yaml
