periodics:
- name: ci-kubernetes-node-release-branch-1-25
  interval: 24h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  decorate: true
  decoration_config:
    timeout: 240m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.25
    path_alias: k8s.io/kubernetes
    workdir: true
  - org: kubernetes
    repo: test-infra
    base_ref: master
    path_alias: k8s.io/test-infra
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
          - --deployment=node
          - --gcp-project-type=node-e2e-project
          - --gcp-zone=us-central1-a
          - --node-args=--image-config-file=/home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/k8s-release-branches/image-config-1.25.yaml
          - '--node-test-args=--container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/usr/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd*\"]}"'
          - --node-tests=true
          - --provider=gce
          - --test_args=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]"
          - --timeout=180m
        env:
          - name: GOPATH
            value: /go
        resources:
          requests:
            memory: "6Gi"
  annotations:
    testgrid-dashboards: sig-node-release-blocking
    testgrid-tab-name: node-conformance-release-1.25
    testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    description: Node conformance tests in release branch 1.25
- name: ci-kubernetes-node-release-branch-1-26
  interval: 24h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  decorate: true
  decoration_config:
    timeout: 240m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.26
    path_alias: k8s.io/kubernetes
    workdir: true
  - org: kubernetes
    repo: test-infra
    base_ref: master
    path_alias: k8s.io/test-infra
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
          - --deployment=node
          - --gcp-project-type=node-e2e-project
          - --gcp-zone=us-central1-a
          - --node-args=--image-config-file=/home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/k8s-release-branches/image-config-1.26.yaml
          - '--node-test-args=--container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/usr/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd*\"]}"'
          - --node-tests=true
          - --provider=gce
          - --test_args=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]"
          - --timeout=180m
        env:
          - name: GOPATH
            value: /go
        resources:
          requests:
            memory: "6Gi"
  annotations:
    testgrid-dashboards: sig-node-release-blocking
    testgrid-tab-name: node-conformance-release-1.26
    testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    description: Node conformance tests in release branch 1.26
- name: ci-kubernetes-node-release-branch-1-27
  interval: 24h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  decorate: true
  decoration_config:
    timeout: 240m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.27
    path_alias: k8s.io/kubernetes
    workdir: true
  - org: kubernetes
    repo: test-infra
    base_ref: master
    path_alias: k8s.io/test-infra
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
          - --deployment=node
          - --gcp-project-type=node-e2e-project
          - --gcp-zone=us-central1-a
          - --node-args=--image-config-file=/home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/k8s-release-branches/image-config-1.27.yaml
          - '--node-test-args=--container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/usr/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd*\"]}"'
          - --node-tests=true
          - --provider=gce
          - --test_args=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]"
          - --timeout=180m
        env:
          - name: GOPATH
            value: /go
        resources:
          requests:
            memory: "6Gi"
  annotations:
    testgrid-dashboards: sig-node-release-blocking
    testgrid-tab-name: node-conformance-release-1.27
    testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    description: Node conformance tests in release branch 1.27
- name: ci-kubernetes-node-release-branch-1-28
  interval: 24h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  decorate: true
  decoration_config:
    timeout: 240m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: release-1.28
    path_alias: k8s.io/kubernetes
    workdir: true
  - org: kubernetes
    repo: test-infra
    base_ref: master
    path_alias: k8s.io/test-infra
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
          - --deployment=node
          - --gcp-project-type=node-e2e-project
          - --gcp-zone=us-central1-a
          - --node-args=--image-config-file=/home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/k8s-release-branches/image-config-1.28.yaml
          - '--node-test-args=--container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/usr/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd*\"]}"'
          - --node-tests=true
          - --provider=gce
          - --test_args=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]"
          - --timeout=180m
        env:
          - name: GOPATH
            value: /go
        resources:
          requests:
            memory: "6Gi"
  annotations:
    testgrid-dashboards: sig-node-release-blocking
    testgrid-tab-name: node-conformance-release-1.28
    testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    description: Node conformance tests in release branch 1.28
