# Distroless images:
# defaultBaseImage: gcr.io/distroless/static:nonroot
baseImageOverrides:
  k8s.io/test-infra/robots/issue-creator: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  k8s.io/test-infra/testgrid/cmd/configurator: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  k8s.io/test-infra/label_sync: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  k8s.io/test-infra/robots/commenter: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  k8s.io/test-infra/robots/pr-creator: gcr.io/k8s-prow/git:v20240129-a0a4e743bf
  k8s.io/test-infra/gcsweb/cmd/gcsweb: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf
  k8s.io/test-infra/gencred: gcr.io/k8s-prow/alpine:v20240129-a0a4e743bf

# https://pkg.go.dev/cmd/link
# -s: omit symbol/debug info
# -w: omit DWARF symbol table
# -X importpath.name=value: sets name to value
builds:
  - id: issue-creator
    dir: .
    main: robots/issue-creator
    ldflags:
      - -s -w
      - -X k8s.io/test-infra/prow/version.Version={{.Env.VERSION}}
      - -X k8s.io/test-infra/prow/version.Name=issue-creator
  - id: configurator
    dir: .
    main: testgrid/cmd/configurator
    ldflags:
      - -s -w
      - -X k8s.io/test-infra/prow/version.Version={{.Env.VERSION}}
      - -X k8s.io/test-infra/prow/version.Name=configurator
  - id: label_sync
    dir: .
    main: label_sync
    ldflags:
      - -s -w
      - -X k8s.io/test-infra/prow/version.Version={{.Env.VERSION}}
      - -X k8s.io/test-infra/prow/version.Name=label_sync
  - id: commenter
    dir: .
    main: robots/commenter
    ldflags:
      - -s -w
      - -X k8s.io/test-infra/prow/version.Version={{.Env.VERSION}}
      - -X k8s.io/test-infra/prow/version.Name=commenter
  - id: pr-creator
    dir: .
    main: robots/pr-creator
    ldflags:
      - -s -w
      - -X k8s.io/test-infra/prow/version.Version={{.Env.VERSION}}
      - -X k8s.io/test-infra/prow/version.Name=pr-creator
  - id: gcsweb-exp
    dir: .
    main: gcsweb/cmd/gcsweb
    ldflags:
      - -s -w
      - -X k8s.io/test-infra/gcsweb/pkg/version.VERSION={{.Env.VERSION}}
  - id: analysis
    dir: .
    main: experiment/ml/analyze
    ldflags:
      - -s -w
