presubmits:
  kubernetes-sigs/container-object-storage-interface-csi-adapter:
  - name: pull-container-object-storage-interface-csi-adapter-build
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/container-object-storage-interface-csi-adapter
    annotations:
      testgrid-dashboards: sig-storage-container-object-storage-interface-csi-adapter
      testgrid-tab-name: build
      description: Build test in container-object-storage-interface-csi-adapter repo.
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.18.4
        command:
        # Plain make runs also verify
        - make
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi

  - name: pull-container-object-storage-interface-csi-adapter-unit
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/container-object-storage-interface-csi-adapter
    annotations:
      testgrid-dashboards: sig-storage-container-object-storage-interface-csi-adapter
      testgrid-tab-name: unit
      description: Unit tests in container-object-storage-interface-csi-adapter repo.
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.18.4
        command:
        - make
        args:
        - test
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
