# sigs.k8s.io/cluster-addons presubmits
presubmits:
  kubernetes-sigs/cluster-addons:
  - name: pull-cluster-addons-unit-test
    decorate: true
    path_alias: sigs.k8s.io/cluster-addons
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230703-e6ae5b372a-master
        command:
        - "./hack/unit-test.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-addons
      testgrid-tab-name: pr-unit-test
