periodics:
- name: periodic-cluster-api-addon-provider-helm-capi-e2e-main
  decorate: true
  decoration_config:
    timeout: 4h
  interval: 12h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-addon-provider-helm
      base_ref: main
      path_alias: "sigs.k8s.io/cluster-api-addon-provider-helm"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240209-9cf7b68bc9-1.29
      command:
        - runner.sh
      args:
        - ./scripts/ci-e2e.sh
      env:
        - name: GINKGO_FOCUS
          value: "Cluster API E2E tests"
        - name: GINKGO_SKIP
          value: "\\[K8s-Upgrade\\]|API Version Upgrade"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-addon-provider-helm
    testgrid-tab-name: caaph-periodic-capi-e2e-main
    testgrid-alert-email: k8s-infra-staging-cluster-api-helm@kubernetes.io
