presubmits:
  kubernetes-sigs/cluster-api-addon-provider-helm:
  - name: pull-cluster-api-addon-provider-helm-build-main
    cluster: eks-prow-build-cluster
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-addon-provider-helm
    always_run: true
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240209-82001bc8c5-1.29
        command:
        - runner.sh
        - ./scripts/ci-build.sh
        resources:
          limits:
            cpu: 6
            memory: 16Gi
          requests:
            cpu: 6
            memory: 16Gi
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-addon-provider-helm
      testgrid-tab-name: caaph-pr-build-main
  - name: pull-cluster-api-addon-provider-helm-apidiff-main
    cluster: eks-prow-build-cluster
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-addon-provider-helm
    always_run: true
    optional: true
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      containers:
      - command:
        - runner.sh
        - ./scripts/ci-apidiff.sh
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240209-82001bc8c5-1.29
        resources:
          limits:
            cpu: 6
            memory: 16Gi
          requests:
            cpu: 6
            memory: 16Gi
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-addon-provider-helm
      testgrid-tab-name: caaph-pr-apidiff-main
  - name: pull-cluster-api-addon-provider-helm-verify-main
    cluster: eks-prow-build-cluster
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-addon-provider-helm
    always_run: true
    labels:
      preset-dind-enabled: "true"
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240209-82001bc8c5-1.29
        command:
        - "runner.sh"
        - ./scripts/ci-verify.sh
        resources:
          limits:
            cpu: 6
            memory: 16Gi
          requests:
            cpu: 6
            memory: 16Gi
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-addon-provider-helm
      testgrid-tab-name: caaph-pr-verify-main
  - name: pull-cluster-api-addon-provider-helm-test-main
    cluster: eks-prow-build-cluster
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-addon-provider-helm
    always_run: true
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240209-82001bc8c5-1.29
        args:
        - runner.sh
        - ./scripts/ci-test.sh
        resources:
          limits:
            cpu: 6
            memory: 16Gi
          requests:
            cpu: 6
            memory: 16Gi
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-addon-provider-helm
      testgrid-tab-name: caaph-pr-test-main
  - name: pull-cluster-api-addon-provider-helm-test-mink8s-main
    cluster: eks-prow-build-cluster
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-addon-provider-helm
    always_run: true
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240209-82001bc8c5-1.29
        args:
        - runner.sh
        - ./scripts/ci-test.sh
        env:
        # This value determines the minimum Kubernetes
        # supported version for Cluster API management cluster.
        #
        # To check the available envtest in Kubebuilder, please
        # refer to https://github.com/kubernetes-sigs/kubebuilder/tree/tools-releases.
        - name: KUBEBUILDER_ENVTEST_KUBERNETES_VERSION
          value: "1.20.2"
        resources:
          limits:
            cpu: 6
            memory: 16Gi
          requests:
            cpu: 6
            memory: 16Gi
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-addon-provider-helm
      testgrid-tab-name: caaph-pr-test-mink8s-main
  - name: pull-cluster-api-addon-provider-helm-e2e
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-addon-provider-helm
    always_run: true
    max_concurrency: 5
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    branches:
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240111-cf1d81388e-1.29
        command:
          - runner.sh
        args:
          - ./scripts/ci-e2e.sh
        env:
          - name: GINKGO_FOCUS
            value: \[REQUIRED\]
          - name: GINKGO_SKIP
            value: ""
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-addon-provider-helm
      testgrid-tab-name: caaph-pr-e2e-main
  - name: pull-cluster-api-addon-provider-helm-capi-e2e-main
    cluster: eks-prow-build-cluster
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-addon-provider-helm
    always_run: true
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240209-82001bc8c5-1.29
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: GINKGO_FOCUS
            value: "Cluster API E2E tests"
          - name: GINKGO_SKIP
            value: "\\[K8s-Upgrade\\]|API Version Upgrade"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
            memory: 32Gi
          limits:
            cpu: 7300m
            memory: 32Gi
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-addon-provider-helm
      testgrid-tab-name: caaph-pr-capi-e2e-main
  - name: pull-cluster-api-addon-provider-helm-e2e-workload-upgrade
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    decoration_config:
      timeout: 4h
    path_alias: sigs.k8s.io/cluster-api-addon-provider-helm
    always_run: true
    branches:
    - ^main$
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240111-cf1d81388e-1.29
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: GINKGO_FOCUS
            value: "\\[K8s-Upgrade\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-addon-provider-helm
      testgrid-tab-name: caaph-pr-e2e-upgrade
  - name: pull-cluster-api-addon-provider-helm-apiversion-upgrade
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-addon-provider-helm
    always_run: true
    branches:
      - ^main$
    extra_refs:
      - org: kubernetes
        repo: kubernetes
        base_ref: master
        path_alias: k8s.io/kubernetes
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240111-cf1d81388e-1.29
          args:
            - runner.sh
            - "./scripts/ci-e2e.sh"
          env:
            - name: GINKGO_FOCUS
              value: "API Version Upgrade"
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 7300m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-addon-provider-helm
      testgrid-tab-name: caaph-pr-apiversion-upgrade-main
      description: This job creates clusters with an older version of Cluster API and Cluster API Add-on Provider Helm, then upgrades them to the latest version of Cluster API and to the main branch of Cluster API Add-on Provider Helm.
