presubmits:
  kubernetes-sigs/node-feature-discovery:
  - name: pull-node-feature-discovery-verify-release-0-14
    cluster: eks-prow-build-cluster
    skip_if_only_changed: "^docs/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    branches:
    - ^release-0.14
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: verify-release-0.14
      description: "Verify source code of node-feature-discovery: check formatting, lint etc."
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.20
        command:
        - scripts/test-infra/verify.sh
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 4
            memory: 8Gi
  - name: pull-node-feature-discovery-verify-docs-release-0-14
    cluster: eks-prow-build-cluster
    run_if_changed: "^docs/"
    branches:
    - ^release-0.14
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: verify-docs-release-0.14
      description: "Verify documentation sources"
    spec:
      containers:
      - image: ruby:slim
        command:
        - scripts/test-infra/mdlint.sh
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
  - name: pull-node-feature-discovery-build-release-0-14
    cluster: eks-prow-build-cluster
    skip_if_only_changed: "^docs/|^demo/|^deployment/|^\\.github/|\\.(md)$|^(README|LICENSE|OWNERS)$"
    branches:
    - ^release-0.14
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-node-feature-discovery
      testgrid-tab-name: build-release-0.14
      description: "Build node-feature-discovery binaries"
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.20
        command:
        - scripts/test-infra/build.sh
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
