# If you are adding new AR regions, you need to run this job for a while and then add the manifests in k/k8s.io
periodics:
  - name: gcr-to-ar-sync-us
    cron: "0 */2 * * *" # 2h
    # cron: "0 0 31 4 *" # 31st of April
    cluster: k8s-infra-prow-build-trusted
    decorate: true
    max_concurrency: 1
    annotations:
      testgrid-dashboards: sig-k8s-infra-k8sio
      testgrid-alert-email: k8s-infra-alerts@kubernetes.io
      testgrid-num-failures-to-alert: '1'
    rerun_auth_config:
      github_team_slugs:
        - org: kubernetes
          slug: sig-k8s-infra-leads
        - org: kubernetes
          slug: release-managers
    spec:
      serviceAccountName: k8s-infra-gcr-promoter
      containers:
        - image: public.ecr.aws/docker/library/golang:1.19
          imagePullPolicy: Always
          command:
            - /bin/bash
          args:
            - -c
            - |
              export PATH=$PATH:$GOPATH/bin
              apt update && apt install parallel -qqy
              go install github.com/google/go-containerregistry/cmd/gcrane@latest
              parallel "gcrane cp --recursive --allow-nondistributable-artifacts us.gcr.io/k8s-artifacts-prod {}-docker.pkg.dev/k8s-artifacts-prod/images" ::: asia-east2 europe-west3 southamerica-east1
              gcrane cp --recursive --allow-nondistributable-artifacts us.gcr.io/k8s-artifacts-prod gcr.io/k8s-artifacts-prod
