images:
    # TODO(mmiranda96): update to cos-109-lts once COS beta promotes to stable
  cos-dev:
    image_family: cos-beta
    project: cos-cloud
    metadata: "user-data</workspace/test-infra/jobs/e2e_node/containerd/init.yaml,cni-template</workspace/test-infra/jobs/e2e_node/containerd/cni.template,containerd-config</workspace/test-infra/jobs/e2e_node/containerd/config-systemd.toml"
