presubmits:
  kubernetes/cloud-provider-openstack:
  - name: pull-cloud-provider-openstack-check
    cluster: eks-prow-build-cluster
    always_run: true
    skip_branches:
    - gh-pages
    labels:
      preset-service-account: "true"
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240209-82001bc8c5-master
        command:
        - runner.sh
        args:
        - make
        - check
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi

  - name: pull-cloud-provider-openstack-test
    cluster: eks-prow-build-cluster
    always_run: true
    skip_branches:
    - gh-pages
    labels:
      preset-service-account: "true"
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240209-82001bc8c5-master
        command:
        - runner.sh
        args:
        - make
        - test
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
