presubmits:
  kubernetes-sigs/controller-runtime:
  - name: pull-controller-runtime-test
    cluster: eks-prow-build-cluster
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/controller-runtime
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.21
        command:
        - ./hack/ci-check-everything.sh
        resources:
          requests:
            cpu: 7
            memory: 14Gi
          limits:
            cpu: 7
            memory: 14Gi
    annotations:
      testgrid-dashboards: sig-api-machinery-kubebuilder
      testgrid-tab-name: controller-runtime-main
  - name: pull-controller-runtime-apidiff
    cluster: eks-prow-build-cluster
    decorate: true
    always_run: true
    optional: true
    path_alias: sigs.k8s.io/controller-runtime
    branches:
    - ^main$
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.21
        command:
        - ./hack/apidiff.sh
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: sig-api-machinery-kubebuilder
      testgrid-tab-name: controller-runtime-main-apidiff
