presubmits:
  kubernetes-sigs/controller-runtime:
  - name: pull-controller-runtime-test-release-0-13
    cluster: eks-prow-build-cluster
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/controller-runtime
    branches:
    - ^release-0.13$
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.19
        command:
        - ./hack/ci-check-everything.sh
        resources:
          requests:
            cpu: 7
            memory: 14Gi
          limits:
            cpu: 7
            memory: 14Gi
    annotations:
      testgrid-dashboards: sig-api-machinery-kubebuilder
      testgrid-tab-name: controller-runtime-release-0.13
  - name: pull-controller-runtime-apidiff-release-0-13
    cluster: eks-prow-build-cluster
    decorate: true
    always_run: true
    optional: true
    path_alias: sigs.k8s.io/controller-runtime
    branches:
    - ^release-0.13$
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.19
        command:
        - ./hack/apidiff.sh
        resources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: sig-api-machinery-kubebuilder
      testgrid-tab-name: controller-runtime-release-0.13-apidiff
