presubmits:
  kubernetes-sigs/controller-runtime:
  - name: pull-controller-runtime-test-release-0-16
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/controller-runtime
    branches:
    - ^release-0.16$
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.20
        command:
        - ./hack/ci-check-everything.sh
        resources:
          requests:
            cpu: "7000m"
    annotations:
      testgrid-dashboards: sig-api-machinery-kubebuilder
      testgrid-tab-name: controller-runtime-release-0.16
  - name: pull-controller-runtime-apidiff-release-0-16
    decorate: true
    always_run: true
    optional: true
    path_alias: sigs.k8s.io/controller-runtime
    branches:
    - ^release-0.16$
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.20
        command:
        - ./hack/apidiff.sh
    annotations:
      testgrid-dashboards: sig-api-machinery-kubebuilder
      testgrid-tab-name: controller-runtime-release-0.16-apidiff
