periodics:
- interval: 6h
  name: periodic-controller-runtime-test
  cluster: eks-prow-build-cluster
  decorate: true
  extra_refs:
  - org: kubernetes-sigs
    repo: controller-runtime
    base_ref: main
  spec:
    containers:
    - image: public.ecr.aws/docker/library/golang:1.21
      command:
      - ./hack/ci-check-everything.sh
      resources:
        requests:
          cpu: 7
          memory: 14Gi
        limits:
          cpu: 7
          memory: 14Gi
  annotations:
    testgrid-dashboards: sig-api-machinery-kubebuilder
    testgrid-tab-name: controller-runtime-periodic-main
