presubmits:
  kubernetes-sigs/controller-runtime:
  - name: pull-controller-runtime-test
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/controller-runtime
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    spec:
      containers:
      - image: golang:1.20
        command:
        - ./hack/ci-check-everything.sh
        resources:
          requests:
            cpu: "7000m"
    annotations:
      testgrid-dashboards: sig-api-machinery-kubebuilder
      testgrid-tab-name: controller-runtime-main
  - name: pull-controller-runtime-apidiff
    decorate: true
    always_run: true
    optional: true
    path_alias: sigs.k8s.io/controller-runtime
    branches:
    - ^main$
    spec:
      containers:
      - image: golang:1.20
        command:
        - ./hack/apidiff.sh
    annotations:
      testgrid-dashboards: sig-api-machinery-kubebuilder
      testgrid-tab-name: controller-runtime-main-apidiff
