periodics:
- interval: 6h
  name: periodic-controller-runtime-test
  decorate: true
  extra_refs:
  - org: kubernetes-sigs
    repo: controller-runtime
    base_ref: main
  spec:
    containers:
    - image: golang:1.20
      command:
      - ./hack/ci-check-everything.sh
      resources:
        requests:
          cpu: "7000m"
  annotations:
    testgrid-dashboards: sig-api-machinery-kubebuilder
    testgrid-tab-name: controller-runtime-periodic-main
