presubmits:
  kubernetes/gengo:
  - name: pull-gengo-test
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-api-machinery-gengo
      testgrid-tab-name: test
    decorate: true
    path_alias: k8s.io/gengo
    always_run: true
    skip_report: false
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
          command:
            - runner.sh
            - bash
          args:
            - -c
            - 'go test -v -race ./... && (cd ./examples/defaulter-gen/_output_tests && go test -v -race ./...)'
          resources:
            requests:
              memory: 4Gi
              cpu: 2
            limits:
              memory: 4Gi
              cpu: 2

  - name: pull-gengo-verify
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-api-machinery-gengo
      testgrid-tab-name: verify
    decorate: true
    path_alias: k8s.io/gengo
    always_run: true
    skip_report: false
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
          command:
            - runner.sh
            - bash
          args:
           - -c
           - hack/verify-examples.sh
          resources:
            requests:
              memory: 4Gi
              cpu: 2
            limits:
              memory: 4Gi
              cpu: 2
