presubmits:
  kubernetes-sigs/kubespray:
  - name: pull-kubespray-yamllint
    cluster: eks-prow-build-cluster
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kubespray
      testgrid-tab-name: yamllint
    always_run: true
    skip_report: false
    decorate: true
    spec:
      containers:
      - image: quay.io/kubespray/kubespray:v2.13.0
        args:
        - yamllint
        - "--strict"
        - .
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 1
            memory: 4Gi
