presubmits:
  kubernetes-sigs/apiserver-network-proxy:
  - name: pull-apiserver-network-proxy-test
    cluster: eks-prow-build-cluster
    always_run: true
    skip_report: false
    decorate: true
    path_alias: sigs.k8s.io/apiserver-network-proxy
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.20
        command:
        - make
        args:
        - test
        resources:
          requests:
            memory: 8Gi
            cpu: 2
          limits:
            memory: 8Gi
            cpu: 2
    annotations:
      testgrid-dashboards: sig-cloud-provider-apiserver-network-proxy
      testgrid-tab-name: pr-test
      description: Tests the apiserver-network-proxy
  - name: pull-apiserver-network-proxy-docker-build-amd64
    cluster: eks-prow-build-cluster
    always_run: true
    skip_report: false
    decorate: true
    path_alias: sigs.k8s.io/apiserver-network-proxy
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230901-e9e5d470a5-1.24
        command:
        - "runner.sh"
        args:
        - make
        - docker-build/proxy-agent-amd64
        env:
        - name: REGISTRY
          value: testlocal.io
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 8Gi
            cpu: 2
          limits:
            memory: 8Gi
            cpu: 2
    annotations:
      testgrid-dashboards: sig-cloud-provider-apiserver-network-proxy
      testgrid-tab-name: pr-docker-build-amd64
      description: Build amd64 image via Docker for the apiserver-network-proxy
  - name: pull-apiserver-network-proxy-docker-build-arm64
    cluster: eks-prow-build-cluster
    always_run: true
    skip_report: false
    decorate: true
    path_alias: sigs.k8s.io/apiserver-network-proxy
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230901-e9e5d470a5-1.24
        command:
        - "runner.sh"
        args:
        - make
        - docker-build/proxy-agent-arm64
        env:
        - name: REGISTRY
          value: testlocal.io
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 8Gi
            cpu: 2
          limits:
            memory: 8Gi
            cpu: 2
    annotations:
      testgrid-dashboards: sig-cloud-provider-apiserver-network-proxy
      testgrid-tab-name: pr-docker-build-arm64
      description: Build arm64 image via Docker for the apiserver-network-proxy
  - name: pull-apiserver-network-proxy-make-lint
    cluster: eks-prow-build-cluster
    always_run: true
    skip_report: false
    decorate: true
    path_alias: sigs.k8s.io/apiserver-network-proxy
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230901-e9e5d470a5-1.24
        command:
        - "runner.sh"
        args:
        - make
        - lint
        resources:
          requests:
            memory: 8Gi
            cpu: 2
          limits:
            memory: 8Gi
            cpu: 2
    annotations:
      testgrid-dashboards: sig-cloud-provider-apiserver-network-proxy
      testgrid-tab-name: pr-make-lint
      description: Run lint target for the apiserver-network-proxy
