images:
  fedora:
    image_family: fedora-coreos-stable
    project: fedora-coreos-cloud
    machine: n1-standard-2
    metadata: "user-data</home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/crio/crio_cgroupsv1.ign"
