images:
  fedora:
    image_family: fedora-coreos-stable
    project: fedora-coreos-cloud
    # Using `n1-standard-4` to enable CPU manager node e2e tests.
    machine: n1-standard-4
    metadata: "user-data</home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/crio/crio_cgroupsv1.ign"
