presubmits:
  kubernetes-sigs/aws-efs-csi-driver:
  - name: pull-aws-efs-csi-driver-verify
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    skip_branches:
    - gh-pages
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        command:
        - runner.sh
        args:
        - make
        - verify
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 1
            memory: 4Gi
    annotations:
      testgrid-dashboards: provider-aws-efs-csi-driver
      testgrid-tab-name: verify
      description: aws efs csi driver basic code verification
      testgrid-num-columns-recent: '30'
  - name: pull-aws-efs-csi-driver-unit
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    skip_branches:
    - gh-pages
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        command:
        - runner.sh
        args:
        - make
        - test
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 1
            memory: 4Gi
    annotations:
      testgrid-dashboards: provider-aws-efs-csi-driver
      testgrid-tab-name: unit-test
      description: aws efs csi driver unit test
      testgrid-num-columns-recent: '30'
  - name: pull-aws-efs-csi-driver-e2e
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    skip_branches:
    - gh-pages
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-aws-credential-aws-shared-testing: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        command:
        - runner.sh
        args:
        - make
        - test-e2e
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: provider-aws-efs-csi-driver
      testgrid-tab-name: e2e-test
      description: aws efs csi driver e2e test
      testgrid-num-columns-recent: '30'
  - name: pull-aws-efs-csi-driver-external-test-eks
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    skip_branches:
      - gh-pages
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-aws-credential-aws-shared-testing: "true"
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
          command:
            - runner.sh
          args:
            - make
            - test-e2e-external-eks
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 2
              memory: 4Gi
    annotations:
      testgrid-dashboards: provider-aws-efs-csi-driver
      testgrid-tab-name: pull-external-test-eks
      description: kubernetes/kubernetes external test on pull request on eks
      testgrid-num-columns-recent: '30'
