periodics:
- interval: 30m
  name: ci-kubernetes-e2e-gci-gce-statefulset
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  decorate: true
  decoration_config:
    timeout: 110m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:StatefulSet\] --minStartupPods=8
      - --timeout=90m
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
  annotations:
    testgrid-dashboards: google-gce
    testgrid-tab-name: gci-gce-statefulset
