presubmits:
  kubernetes-sigs/release-utils:
  - name: pull-release-utils-test
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/release-utils"
    cluster: eks-prow-build-cluster
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.21-bookworm
        imagePullPolicy: Always
        command:
        - go
        args:
        - run
        - mage.go
        - Test
        resources:
          limits:
            cpu: 4
            memory: 6Gi
          requests:
            cpu: 4
            memory: 6Gi
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: release-utils-test
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
  - name: pull-release-utils-verify
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/release-utils"
    cluster: eks-prow-build-cluster
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.21-bookworm
        imagePullPolicy: Always
        command:
        - go
        args:
        - run
        - mage.go
        - Verify
        resources:
          limits:
            cpu: 4
            memory: 6Gi
          requests:
            cpu: 4
            memory: 6Gi
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: release-utils-verify
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
