presubmits:
  kubernetes-sigs/alibaba-cloud-csi-driver:

  - name: pull-alibaba-cloud-csi-driver-verify-fmt
    cluster: k8s-infra-prow-build
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240219-207a9fb4d2-master
        command:
        - make
        args:
        - fmt
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: presubmits-alibaba-cloud-csi-driver
      testgrid-tab-name: pr-verify-fmt
      description: Verifies the Golang sources have been formatted

  - name: pull-alibaba-cloud-csi-driver-verify-lint
    cluster: k8s-infra-prow-build
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240219-207a9fb4d2-master
        command:
        - make
        args:
        - lint
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: presubmits-alibaba-cloud-csi-driver
      testgrid-tab-name: pr-verify-lint
      description: Verifies the Golang sources are linted

  - name: pull-alibaba-cloud-csi-driver-verify-vet
    cluster: k8s-infra-prow-build
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240219-207a9fb4d2-master
        command:
        - make
        args:
        - vet
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: presubmits-alibaba-cloud-csi-driver
      testgrid-tab-name: pr-verify-vet
      description: Vets the Golang sources have been vetted

  - name: pull-alibaba-cloud-csi-driver-verify-unit
    cluster: k8s-infra-prow-build
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240219-207a9fb4d2-master
        command:
        - make
        args:
        - test
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: presubmits-alibaba-cloud-csi-driver
      testgrid-tab-name: pr-verify-unit
      description: Alibaba cloud csi driver unit test
