steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --tag=gcr.io/$PROJECT_ID/triage:$_GIT_TAG
  - .
- name: gcr.io/cloud-builders/docker
  args:
  - tag
  - gcr.io/$PROJECT_ID/triage:$_GIT_TAG
  - gcr.io/$PROJECT_ID/triage:latest
  env:
  - _=$_PULL_BASE_REF # unused
substitutions:
  # variables set by kubernetes/test-infra/images/builder
  # set by image-builder to vYYYYMMDD-hash
  _GIT_TAG: '12345'
  # set by image-builder to branch name; we don't use this, but we
  # want strict validation of substitution vars to catch typos early
  _PULL_BASE_REF: 'main'
images:
  - 'gcr.io/$PROJECT_ID/triage:$_GIT_TAG'
  - 'gcr.io/$PROJECT_ID/triage:latest'
