periodics:
- name: maintenance-ci-scale-aws-janitor
  cluster: eks-prow-build-cluster
  interval: 1h
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential-boskos-scale-001-kops: "true"
  decorate: true
  spec:
    containers:
    - command:
      - /app
      args:
      - --ttl=12h
      - --path=s3://k8s-infra-kops-scale-tests/objs.json
      image: gcr.io/k8s-staging-boskos/aws-janitor:v20230908-da54d76
      resources:
        requests:
          cpu: 1
          memory: "2Gi"
        limits:
          cpu: 1
          memory: "2Gi"
  annotations:
    testgrid-dashboards: sig-testing-maintenance
    testgrid-tab-name: ci-scale-aws-janitor
    description: Deletes old AWS resources for scalability jobs

- name: ci-kubernetes-e2e-kops-aws-scale-amazonvpc-using-cl2
  tags:
  - "perfDashPrefix: aws-5000Nodes"
  - "perfDashBuildsCount: 270"
  - "perfDashJobType: performance"
  cluster: eks-prow-build-cluster
  interval: 24h
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential-boskos-scale-001-kops: "true"
    preset-dind-enabled: "true"
  decorate: true
  decoration_config:
    timeout: 480m
  extra_refs:
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  - org: kubernetes
    repo: perf-tests
    base_ref: master
    path_alias: k8s.io/perf-tests
  - org: kubernetes
    repo: kops
    base_ref: master
    path_alias: k8s.io/kops
    workdir: true
  annotations:
    test.kops.k8s.io/cloud: aws
    test.kops.k8s.io/distro: u2204
    test.kops.k8s.io/k8s_version: stable
    test.kops.k8s.io/kops_channel: alpha
    test.kops.k8s.io/networking: amazonvpc
    testgrid-dashboards: kops-misc, sig-cluster-lifecycle-kops, sig-scalability-aws
    testgrid-tab-name: ec2-master-scale-performance
    testgrid-alert-email: kubernetes-sig-scale@googlegroups.com, kubernetes-scalability-tickets@google.com, eks-scalability@amazon.com
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
      imagePullPolicy: Always
      command:
      - runner.sh
      args:
      - ./tests/e2e/scenarios/scalability/run-test.sh
      securityContext:
        privileged: true
      env:
      - name: KUBE_SSH_KEY_PATH
        value: /etc/aws-ssh/aws-ssh-private
      - name: KUBE_SSH_USER
        value: ubuntu
      - name: GOPATH
        value: /home/prow/go
      - name: ARTIFACTS
        value: $(ARTIFACTS)
      - name: CNI_PLUGIN
        value: "amazonvpc"
      - name: KUBE_NODE_COUNT
        value: "5000"
      - name: CL2_LOAD_TEST_THROUGHPUT
        value: "50"
      - name: CL2_DELETE_TEST_THROUGHPUT
        value: "50"
      - name: CL2_RATE_LIMIT_POD_CREATION
        value: "false"
      - name: NODE_MODE
        value: "master"
      - name: CONTROL_PLANE_COUNT
        value: "3"
      - name: CONTROL_PLANE_SIZE
        value: "c5.18xlarge"
      - name: KOPS_STATE_STORE
        value: "s3://k8s-infra-kops-scale-tests"
      - name: PROMETHEUS_SCRAPE_KUBE_PROXY
        value: "true"
      - name: CL2_ENABLE_DNS_PROGRAMMING
        value: "true"
      - name: CL2_ENABLE_API_AVAILABILITY_MEASUREMENT
        value: "true"
      - name: CL2_API_AVAILABILITY_PERCENTAGE_THRESHOLD
        value: "99.5"
      - name: CL2_ALLOWED_SLOW_API_CALLS
        value: "1"
      - name: ENABLE_PROMETHEUS_SERVER
        value: "true"
      - name: PROMETHEUS_PVC_STORAGE_CLASS
        value: "gp2"
      - name: CLOUD_PROVIDER
        value: "aws"
      - name: CLUSTER_NAME
        value: "scale-1000.periodic.test-cncf-aws.k8s.io"
      - name: KOPS_IRSA
        value: "true"
      resources:
        requests:
          cpu: "10"
          memory: "48Gi"
        limits:
          cpu: "10"
          memory: "48Gi"
