presubmits:
  kubernetes-sigs/zeitgeist:
  - name: pull-zeitgeist-build
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/zeitgeist"
    cluster: eks-prow-build-cluster
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.21-bookworm
        imagePullPolicy: Always
        command:
        - make
        - build
        resources:
          limits:
            cpu: 4
            memory: 6Gi
          requests:
            cpu: 4
            memory: 6Gi
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: zeitgeist-build
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
  - name: pull-zeitgeist-test
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/zeitgeist"
    cluster: eks-prow-build-cluster
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.21-bookworm
        imagePullPolicy: Always
        command:
        - make
        - test
        resources:
          limits:
            cpu: 4
            memory: 6Gi
          requests:
            cpu: 4
            memory: 6Gi
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: zeitgeist-test
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
  - name: pull-zeitgeist-verify
    always_run: true
    decorate: true
    path_alias: "sigs.k8s.io/zeitgeist"
    cluster: eks-prow-build-cluster
    spec:
      containers:
      - image: gcr.io/k8s-staging-releng/releng-ci:latest-go1.21-bookworm
        imagePullPolicy: Always
        command:
        - make
        - verify
        resources:
          limits:
            cpu: 4
            memory: 6Gi
          requests:
            cpu: 4
            memory: 6Gi
    annotations:
      testgrid-dashboards: sig-release-releng-presubmits
      testgrid-tab-name: zeitgeist-verify
      testgrid-alert-email: release-managers+alerts@kubernetes.io
      testgrid-num-columns-recent: '30'
