periodics:

- name: periodic-cluster-api-e2e-workload-upgrade-1-22-1-23-release-1-5
  cluster: eks-prow-build-cluster
  interval: 24h
  decorate: true
  rerun_auth_config:
    github_team_slugs:
    - org: kubernetes-sigs
      slug: cluster-api-maintainers
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.5
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-1.27
      args:
        - runner.sh
        - "./scripts/ci-e2e.sh"
      env:
        - name: ALWAYS_BUILD_KIND_IMAGES
          value: "true"
        - name: KUBERNETES_VERSION_UPGRADE_FROM
          value: "stable-1.22"
        - name: KUBERNETES_VERSION_UPGRADE_TO
          value: "stable-1.23"
        - name: ETCD_VERSION_UPGRADE_TO
          value: "3.5.3-0"
        - name: COREDNS_VERSION_UPGRADE_TO
          value: "v1.8.6"
        - name: GINKGO_FOCUS
          value: "\\[K8s-Upgrade\\]"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
          memory: 32Gi
        limits:
          cpu: 7300m
          memory: 32Gi
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.5
    testgrid-tab-name: capi-e2e-release-1-5-1-22-1-23
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"

- name: periodic-cluster-api-e2e-workload-upgrade-1-23-1-24-release-1-5
  cluster: eks-prow-build-cluster
  interval: 24h
  decorate: true
  rerun_auth_config:
    github_team_slugs:
    - org: kubernetes-sigs
      slug: cluster-api-maintainers
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.5
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-1.27
      args:
      - runner.sh
      - "./scripts/ci-e2e.sh"
      env:
      - name: ALWAYS_BUILD_KIND_IMAGES
        value: "true"
      - name: KUBERNETES_VERSION_UPGRADE_FROM
        value: "stable-1.23"
      - name: KUBERNETES_VERSION_UPGRADE_TO
        value: "stable-1.24"
      - name: ETCD_VERSION_UPGRADE_TO
        value: "3.5.3-0"
      - name: COREDNS_VERSION_UPGRADE_TO
        value: "v1.8.6"
      - name: GINKGO_FOCUS
        value: "\\[K8s-Upgrade\\]"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
          memory: 32Gi
        limits:
          cpu: 7300m
          memory: 32Gi
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.5
    testgrid-tab-name: capi-e2e-release-1-5-1-23-1-24
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"

- name: periodic-cluster-api-e2e-workload-upgrade-1-24-1-25-release-1-5
  cluster: eks-prow-build-cluster
  interval: 24h
  decorate: true
  rerun_auth_config:
    github_team_slugs:
    - org: kubernetes-sigs
      slug: cluster-api-maintainers
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api
      base_ref: release-1.5
      path_alias: sigs.k8s.io/cluster-api
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-1.27
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: ALWAYS_BUILD_KIND_IMAGES
            value: "true"
          - name: KUBERNETES_VERSION_UPGRADE_FROM
            value: "stable-1.24"
          - name: KUBERNETES_VERSION_UPGRADE_TO
            value: "stable-1.25"
          - name: ETCD_VERSION_UPGRADE_TO
            value: "3.5.4-0"
          - name: COREDNS_VERSION_UPGRADE_TO
            value: "v1.9.3"
          - name: GINKGO_FOCUS
            value: "\\[K8s-Upgrade\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
            memory: 32Gi
          limits:
            cpu: 7300m
            memory: 32Gi
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.5
    testgrid-tab-name: capi-e2e-release-1-5-1-24-1-25
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"

- name: periodic-cluster-api-e2e-workload-upgrade-1-25-1-26-release-1-5
  cluster: eks-prow-build-cluster
  interval: 24h
  decorate: true
  rerun_auth_config:
    github_team_slugs:
    - org: kubernetes-sigs
      slug: cluster-api-maintainers
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api
      base_ref: release-1.5
      path_alias: sigs.k8s.io/cluster-api
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-1.27
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: ALWAYS_BUILD_KIND_IMAGES
            value: "true"
          - name: KUBERNETES_VERSION_UPGRADE_FROM
            value: "stable-1.25"
          - name: KUBERNETES_VERSION_UPGRADE_TO
            value: "stable-1.26"
          - name: ETCD_VERSION_UPGRADE_TO
            value: "3.5.6-0"
          - name: COREDNS_VERSION_UPGRADE_TO
            value: "v1.9.3"
          - name: GINKGO_FOCUS
            value: "\\[K8s-Upgrade\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
            memory: 32Gi
          limits:
            cpu: 7300m
            memory: 32Gi
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.5
    testgrid-tab-name: capi-e2e-release-1-5-1-25-1-26
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"

- name: periodic-cluster-api-e2e-workload-upgrade-1-26-1-27-release-1-5
  cluster: eks-prow-build-cluster
  interval: 24h
  decorate: true
  rerun_auth_config:
    github_team_slugs:
    - org: kubernetes-sigs
      slug: cluster-api-maintainers
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.5
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-1.27
      args:
      - runner.sh
      - "./scripts/ci-e2e.sh"
      env:
      - name: ALWAYS_BUILD_KIND_IMAGES
        value: "true"
      - name: KUBERNETES_VERSION_UPGRADE_FROM
        value: "stable-1.26"
      - name: KUBERNETES_VERSION_UPGRADE_TO
        value: "stable-1.27"
      - name: ETCD_VERSION_UPGRADE_TO
        value: "3.5.6-0"
      - name: COREDNS_VERSION_UPGRADE_TO
        value: "v1.9.3"
      - name: GINKGO_FOCUS
        value: "\\[K8s-Upgrade\\]"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
          memory: 32Gi
        limits:
          cpu: 7300m
          memory: 32Gi
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.5
    testgrid-tab-name: capi-e2e-release-1-5-1-26-1-27
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"

- name: periodic-cluster-api-e2e-workload-upgrade-1-27-1-28-release-1-5
  cluster: eks-prow-build-cluster
  interval: 24h
  decorate: true
  rerun_auth_config:
    github_team_slugs:
    - org: kubernetes-sigs
      slug: cluster-api-maintainers
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.5
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-1.27
      args:
      - runner.sh
      - "./scripts/ci-e2e.sh"
      env:
      - name: ALWAYS_BUILD_KIND_IMAGES
        value: "true"
      - name: KUBERNETES_VERSION_UPGRADE_FROM
        value: "stable-1.27"
      - name: KUBERNETES_VERSION_UPGRADE_TO
        value: "stable-1.28"
      - name: ETCD_VERSION_UPGRADE_TO
        value: "3.5.9-0"
      - name: COREDNS_VERSION_UPGRADE_TO
        value: "v1.10.1"
      - name: GINKGO_FOCUS
        value: "\\[K8s-Upgrade\\]"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
          memory: 32Gi
        limits:
          cpu: 7300m
          memory: 32Gi
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.5
    testgrid-tab-name: capi-e2e-release-1-5-1-27-1-28
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
