periodics:
- name: periodic-cluster-api-test-release-1-4
  cluster: eks-prow-build-cluster
  interval: 4h
  decorate: true
  rerun_auth_config:
    github_team_slugs:
      - org: kubernetes-sigs
        slug: cluster-api-maintainers
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api
      base_ref: release-1.4
      path_alias: sigs.k8s.io/cluster-api
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-1.26
        command:
          - runner.sh
          - ./scripts/ci-test.sh
        resources:
          requests:
            cpu: 7300m
            memory: 9Gi
          limits:
            cpu: 7300m
            memory: 9Gi
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.4
    testgrid-tab-name: capi-test-release-1-4
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
- name: periodic-cluster-api-test-mink8s-release-1-4
  cluster: eks-prow-build-cluster
  interval: 4h
  decorate: true
  rerun_auth_config:
    github_team_slugs:
      - org: kubernetes-sigs
        slug: cluster-api-maintainers
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api
      base_ref: release-1.4
      path_alias: sigs.k8s.io/cluster-api
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-1.26
        command:
          - runner.sh
          - ./scripts/ci-test.sh
        env:
          # This value determines the minimum Kubernetes
          # supported version for Cluster API management cluster.
          #
          # To check the available envtest in Kubebuilder, please
          # refer to https://github.com/kubernetes-sigs/kubebuilder/tree/tools-releases.
          - name: KUBEBUILDER_ENVTEST_KUBERNETES_VERSION
            value: "1.23.5"
        resources:
          requests:
            cpu: 7300m
            memory: 9Gi
          limits:
            cpu: 7300m
            memory: 9Gi
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.4
    testgrid-tab-name: capi-test-mink8s-release-1-4
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
- name: periodic-cluster-api-e2e-release-1-4
  cluster: eks-prow-build-cluster
  interval: 4h
  decorate: true
  rerun_auth_config:
    github_team_slugs:
      - org: kubernetes-sigs
        slug: cluster-api-maintainers
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api
      base_ref: release-1.4
      path_alias: sigs.k8s.io/cluster-api
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-1.26
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: GINKGO_SKIP
            value: "\\[Conformance\\] \\[K8s-Upgrade\\]|\\[IPv6\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
            memory: 32Gi
          limits:
            cpu: 7300m
            memory: 32Gi
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.4
    testgrid-tab-name: capi-e2e-release-1-4
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
- name: periodic-cluster-api-e2e-mink8s-release-1-4
  cluster: eks-prow-build-cluster
  interval: 4h
  decorate: true
  rerun_auth_config:
    github_team_slugs:
      - org: kubernetes-sigs
        slug: cluster-api-maintainers
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api
      base_ref: release-1.4
      path_alias: sigs.k8s.io/cluster-api
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-1.26
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: GINKGO_SKIP
            value: "\\[Conformance\\] \\[K8s-Upgrade\\]|\\[IPv6\\]"
          # This value determines the minimum Kubernetes
          # supported version for Cluster API management cluster.
          - name: KUBERNETES_VERSION_MANAGEMENT
            value: "v1.23.17"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
            memory: 32Gi
          limits:
            cpu: 7300m
            memory: 32Gi
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.4
    testgrid-tab-name: capi-e2e-mink8s-release-1-4
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
