presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-apidiff
    cluster: eks-prow-build-cluster
    # A job which automatically runs for changes in staging and then only
    # diffs staging might be useful. For now, this checks everything and
    # has to be started manually with:
    #   /test pull-kubernetes-apidiff
    always_run: false
    optional: true
    decorate: true
    annotations:
      # The apidiff.sh script uses the latest revision of apidiff.
      # There is no guarantee that this will continue to work for
      # older branches, so let's not even create per-release
      # copies of this job.
      fork-per-release: "false"
      testgrid-dashboards: sig-testing-misc
      testgrid-create-test-group: 'true'
    path_alias: k8s.io/kubernetes
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240506-e1212ac574-master
        imagePullPolicy: Always
        command:
        - runner.sh
        args:
        - /bin/sh
        - -c
        # PULL_BASE_SHA is the revision on the target branch that the
        # PR gets merged into. What we want instead is the revision at
        # which the PR branch diverged from the target branch.
        # We get that from "git merge-base".
        - "./hack/apidiff.sh -r $(git merge-base ${PULL_BASE_SHA} ${PULL_PULL_SHA}) -t ${PULL_PULL_SHA}"
        env:
        - name: REPO_DIR
          value: /workspace/k8s.io/kubernetes
        resources:
          # Memory limits are derived from pull-kubernetes-verify, with less CPUs.
          limits:
            cpu: 2
            memory: 12Gi
          requests:
            cpu: 2
            memory: 12Gi

# A periodic job which shows API diffs for staging repos since the last release
# might be useful. Not done yet.
