# k8s.io/kubeadm presubmits
presubmits:
  kubernetes/kubeadm:

  # kinder presubmits
  - name: pull-kubeadm-kinder-verify
    decorate: true
    optional: false
    path_alias: "k8s.io/kubeadm"
    run_if_changed: '^kinder\/.*$'
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        command:
        - "./kinder/hack/verify-all.sh"

  - name: pull-kubeadm-kinder-upgrade-latest
    decorate: true
    optional: false
    run_if_changed: '^kinder\/.*$'
    skip_branches:
    - release-\d+\.\d+ # revisit once the k/kubeadm repo has branches
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decoration_config:
      timeout: 40m
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
        command:
        - runner.sh
        - "../kubeadm/kinder/ci/kinder-run.sh"
        args:
        - "presubmit-upgrade-latest"
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "9000Mi"
            cpu: 2000m
