presubmits:
  kubernetes-sigs/secrets-store-sync-controller:
  - name: pull-secrets-store-sync-controller-lint
    cluster: eks-prow-build-cluster
    decorate: true
    decoration_config:
      timeout: 10m
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-sync-controller
    branches:
    - ^main$
    - ^release-*
    labels:
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240515-17c6d50e24-master
        command:
          - runner.sh
        args:
          - make
          - test-style
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-sync-controller
      testgrid-tab-name: pr-secrets-store-sync-controller-lint
      description: "Run linting rules for Secrets Store Sync Controller."
      testgrid-num-columns-recent: '30'
  - name: pull-secrets-store-sync-controller-unit
    cluster: eks-prow-build-cluster
    decorate: true
    decoration_config:
      timeout: 10m
    always_run: true
    path_alias: sigs.k8s.io/secrets-store-sync-controller
    branches:
    - ^main$
    - ^release-*
    labels:
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240515-17c6d50e24-master
        command:
          - runner.sh
        args:
          - make
          - test
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
    annotations:
      testgrid-dashboards: sig-auth-secrets-store-sync-controller
      testgrid-tab-name: pr-secrets-store-sync-controller-unit
      description: "Run unit tests for Secrets Store Sync Controller."
      testgrid-num-columns-recent: '30'
