presubmits:
  kubernetes/client-go:
  - name: pull-client-go-build
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    path_alias: k8s.io/client-go
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.15.8
        env:
        - name: GO111MODULE
          value: "on"
        command:
        - go
        args:
        - build
        - ./...
        resources:
          requests:
            memory: 4Gi
            cpu: 2
          limits:
            memory: 4Gi
            cpu: 2
