presubmits:
  kubernetes/enhancements:
    - name: pull-enhancements-verify
      cluster: eks-prow-build-cluster
      always_run: true
      decorate: true
      spec:
        containers:
          - image: public.ecr.aws/docker/library/golang:1.17
            command:
              - sh
              - "-c"
              - "export PATH=$PATH:$GOPATH/bin && ./hack/verify.sh"
            resources:
              limits:
                cpu: 2
                memory: 4Gi
              requests:
                cpu: 2
                memory: 4Gi
    - name: pull-enhancements-test
      cluster: eks-prow-build-cluster
      always_run: true
      decorate: true
      spec:
        containers:
          - image: public.ecr.aws/docker/library/golang:1.17
            command:
              - make
              - test
              - tools
            resources:
              limits:
                cpu: 2
                memory: 4Gi
              requests:
                cpu: 2
                memory: 4Gi
