presubmits:
  etcd-io/etcd:
  - name: pull-etcd-build
    cluster: eks-prow-build-cluster
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-build
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240611-597c402033-master
        command:
        - runner.sh
        args:
        - make
        - build-all
        resources:
          requests:
            cpu: "4"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "4Gi"

  - name: pull-etcd-unit-test-amd64
    cluster: eks-prow-build-cluster
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-unit-test-amd64
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240611-597c402033-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - |
          export JUNIT_REPORT_DIR=${ARTIFACTS}
          GOOS=linux GOARCH=amd64 CPU=4 GO_TEST_FLAGS='-p=2' make test-unit
        resources:
          requests:
            cpu: "4"
            memory: "2Gi"
          limits:
            cpu: "4"
            memory: "2Gi"

  - name: pull-etcd-unit-test-386
    cluster: eks-prow-build-cluster
    optional: true # remove this once the job is green
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-unit-test-386
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240611-597c402033-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - |
          export JUNIT_REPORT_DIR=${ARTIFACTS}
          GOOS=linux GOARCH=386 CPU=1 GO_TEST_FLAGS='-p=4' make test-unit
        resources:
          requests:
            cpu: "4"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "4Gi"

  - name: pull-etcd-verify
    cluster: eks-prow-build-cluster
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-verify
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240611-597c402033-master
        command:
        - /bin/bash
        args:
        - -c
        - |
          set -euo pipefail
          export PATH=$GOPATH/bin:$PATH && make verify
          export PATH=$GOPATH/bin:$PATH && make fix
          DIFF=$(git status --porcelain)
          if [ -n "$DIFF" ]; then
            echo "These files were modified:"
            echo
            echo "$DIFF"
            echo
            exit 1
          fi
        resources:
          requests:
            cpu: "4"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "4Gi"

  - name: pull-etcd-e2e-amd64
    cluster: eks-prow-build-cluster
    optional: true # remove this once the job is green
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-e2e-amd64
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240611-597c402033-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - |
          set -euo pipefail
          make gofail-enable
          VERBOSE=1 GOOS=linux GOARCH=amd64 CPU=4 EXPECT_DEBUG=true make test-e2e-release
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "8Gi"

  - name: pull-etcd-integration-1-cpu-amd64
    cluster: eks-prow-build-cluster
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-integration-1-cpu-amd64
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240611-597c402033-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - |
          set -euo pipefail
          make gofail-enable
          GOOS=linux GOARCH=amd64 CPU=1 make test-integration
        resources:
          requests:
            cpu: "2"
            memory: "3Gi"
          limits:
            cpu: "2"
            memory: "3Gi"

  - name: pull-etcd-integration-2-cpu-amd64
    cluster: eks-prow-build-cluster
    optional: true # remove this once the job is green
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-integration-2-cpu-amd64
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240611-597c402033-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - |
          set -euo pipefail
          make gofail-enable
          GOOS=linux GOARCH=amd64 CPU=2 make test-integration
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
          limits:
            cpu: "2"
            memory: "8Gi"

  - name: pull-etcd-integration-4-cpu-amd64
    cluster: eks-prow-build-cluster
    optional: true # remove this once the job is green
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-integration-4-cpu-amd64
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240611-597c402033-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - |
          set -euo pipefail
          make gofail-enable
          GOOS=linux GOARCH=amd64 CPU=4 make test-integration
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "8Gi"

  - name: pull-etcd-robustness-amd64
    cluster: k8s-infra-prow-build
    optional: true # remove this once the job is green
    always_run: true
    branches:
      - main
    decorate: true
    decoration_config:
      timeout: 60m
    annotations:
      testgrid-dashboards: sig-etcd-presubmits, sig-etcd-robustness
      testgrid-tab-name: pull-etcd-robustness-amd64
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240611-597c402033-master
          command:
            - runner.sh
          args:
            - bash
            - -c
            - |
              return_code=0
              apt-get -o APT::Update::Error-Mode=any update && apt-get --yes install cmake libfuse3-dev libfuse3-3 fuse3
              sed -i 's/#user_allow_other/user_allow_other/g' /etc/fuse.conf
              make install-lazyfs
              set -euo pipefail
              go clean -testcache
              GO_TEST_FLAGS="-v --count 12 --timeout '30m' --run TestRobustness"
              VERBOSE=1 GOOS=linux GOARCH=amd64 CPU=8 EXPECT_DEBUG=true GO_TEST_FLAGS=${GO_TEST_FLAGS} RESULTS_DIR=/tmp/results make test-robustness-main || return_code=$?
              if [ -d /tmp/results ]; then
                zip -r ${ARTIFACTS}/results.zip /tmp/results
              fi
              exit $return_code
          resources:
            requests:
              cpu: "7"
              memory: "14Gi"
            limits:
              cpu: "7"
              memory: "14Gi"
