presubmits:
  etcd-io/etcd:
  - name: pull-etcd-build
    cluster: eks-prow-build-cluster
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-build
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240515-17c6d50e24-master
        command:
        - runner.sh
        args:
        - make
        - build-all
        resources:
          requests:
            cpu: "4"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "4Gi"

  - name: pull-etcd-unit-test
    cluster: eks-prow-build-cluster
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-unit-test
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240515-17c6d50e24-master
        command:
        - runner.sh
        args:
        - make
        - test-unit
        resources:
          requests:
            cpu: "4"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "4Gi"

  - name: pull-etcd-verify
    cluster: eks-prow-build-cluster
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-verify
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240515-17c6d50e24-master
        command:
        - /bin/bash
        args:
        - -c
        - |
          set -euo pipefail
          export PATH=$GOPATH/bin:$PATH && make verify
          export PATH=$GOPATH/bin:$PATH && make fix
          DIFF=$(git status --porcelain)
          if [ -n "$DIFF" ]; then
            echo "These files were modified:"
            echo
            echo "$DIFF"
            echo
            exit 1
          fi
        resources:
          requests:
            cpu: "4"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "4Gi"

  - name: pull-etcd-e2e-amd64
    cluster: eks-prow-build-cluster
    optional: true # remove this once the job is green
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-e2e-amd64
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240515-17c6d50e24-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - |
          set -euo pipefail
          make gofail-enable
          VERBOSE=1 GOOS=linux GOARCH=amd64 CPU=4 EXPECT_DEBUG=true make test-e2e-release
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "8Gi"

  - name: pull-etcd-integration-1-cpu-amd64
    cluster: eks-prow-build-cluster
    optional: true # remove this once the job is green
    always_run: true
    branches:
    - main
    decorate: true
    annotations:
      testgrid-dashboards: sig-etcd-presubmits
      testgrid-tab-name: pull-etcd-integration-1-cpu-amd64
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240515-17c6d50e24-master
        command:
        - runner.sh
        args:
        - bash
        - -c
        - |
          set -euo pipefail
          make gofail-enable
          GOOS=linux GOARCH=amd64 CPU=1 make test-integration
        resources:
          requests:
            cpu: "2"
            memory: "3Gi"
          limits:
            cpu: "2"
            memory: "3Gi"
