#
# Start dashboards
#
dashboards:
- name: amazon-ec2
- name: amazon-ec2-node
- name: amazon-ec2-al2023
- name: amazon-ec2-provider
- name: amazon-ec2-release
- name: amazon-ec2-periodics
- name: amazon-ec2-presubmits

#
# Start dashboard groups
#
dashboard_groups:
- name: amazon
  dashboard_names:
  - amazon-ec2
  - amazon-ec2-node
  - amazon-ec2-al2023
  - amazon-ec2-provider
  - amazon-ec2-release
  - amazon-ec2-periodics
  - amazon-ec2-presubmits
