presubmits:
  kubernetes-sigs/controller-tools:
  - name: pull-controller-tools-test-master
    cluster: eks-prow-build-cluster
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/controller-tools
    branches:
    - ^master$
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.20
        command:
        - make
        - test-all
        resources:
          limits:
            cpu: 10
            memory: 24Gi
          requests:
            cpu: 10
            memory: 24Gi
    annotations:
      testgrid-dashboards: sig-api-machinery-kubebuilder
      testgrid-tab-name: controller-tools-master
