presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-gce-storage-slow
    cluster: k8s-infra-prow-build
    always_run: false
    optional: true
    # All the files owned by sig-storage. Keep in sync across
    # all sig-storage-jobs
    #
    # pkg/controller/volume
    # pkg/kubelet/volumemanager
    # pkg/volume
    # pkg/util/mount
    # test/e2e/storage
    # test/e2e/testing-manifests/storage-csi
    run_if_changed: '^(pkg\/controller\/volume|pkg\/kubelet\/volumemanager|pkg\/volume|pkg\/util\/mount|test\/e2e\/storage|test\/e2e\/testing-manifests\/storage-csi)'
    branches:
    # TODO(releng): Remove once repo default branch has been renamed
    - master
    - main
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-dind-enabled: "true"
      preset-pull-kubernetes-e2e: "true"
      preset-pull-kubernetes-e2e-gce: "true"
    decorate: true
    decoration_config:
      timeout: 150m
    path_alias: k8s.io/kubernetes
    extra_refs:
    - org: kubernetes
      repo: release
      base_ref: master
      path_alias: k8s.io/release
    spec:
      containers:
      - command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --build=quick
        - --cluster=
        - --extract=local
        - --gcp-node-image=gci
        - --gcp-zone=us-west1-b
        - --ginkgo-parallel=30
        - --provider=gce
        - --stage=gs://k8s-release-pull/ci/pull-kubernetes-e2e-gce-storage-slow
        - --test_args=--ginkgo.focus=\[sig-storage\].*\[Slow\] --ginkgo.skip=\[Driver:.gcepd\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
        - --timeout=120m
        securityContext:
          privileged: true
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240311-b09cdeb92c-master
        resources:
          limits:
            cpu: "4"
            memory: "6Gi"
          requests:
            cpu: "4"
            memory: "6Gi"
    annotations:
      testgrid-create-test-group: 'true'
  - name: pull-kubernetes-e2e-gce-storage-snapshot
    cluster: k8s-infra-prow-build
    always_run: false
    optional: true
    # All the files owned by sig-storage. Keep in sync across
    # all sig-storage-jobs
    #
    # pkg/controller/volume
    # pkg/kubelet/volumemanager
    # pkg/volume
    # pkg/util/mount
    # test/e2e/storage
    # test/e2e/testing-manifests/storage-csi
    run_if_changed: '^(pkg\/controller\/volume|pkg\/kubelet\/volumemanager|pkg\/volume|pkg\/util\/mount|test\/e2e\/storage|test\/e2e\/testing-manifests\/storage-csi)'
    branches:
    # TODO(releng): Remove once repo default branch has been renamed
    - master
    - main
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-dind-enabled: "true"
      preset-pull-kubernetes-e2e: "true"
      preset-pull-kubernetes-e2e-gce: "true"
    decorate: true
    decoration_config:
      timeout: 180m
    path_alias: k8s.io/kubernetes
    extra_refs:
    - org: kubernetes
      repo: release
      base_ref: master
      path_alias: k8s.io/release
    spec:
      containers:
      - command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --build=quick
        - --cluster=
        - --extract=local
        - --gcp-node-image=gci
        - --gcp-zone=us-west1-b
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-storage-snapshot
        - --test_args=--ginkgo.focus=\[Feature:VolumeSnapshotDataSource\] --ginkgo.skip=\[Disruptive\]|\[Flaky\] --minStartupPods=8
        - --timeout=150m
        securityContext:
          privileged: true
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240311-b09cdeb92c-master
        resources:
          limits:
            cpu: "4"
            memory: "6Gi"
          requests:
            cpu: "4"
            memory: "6Gi"
    annotations:
      testgrid-create-test-group: 'true'
  - name: pull-kubernetes-e2e-gce-csi-serial
    cluster: k8s-infra-prow-build
    always_run: false
    optional: true
    # All the files owned by sig-storage. Keep in sync across
    # all sig-storage-jobs
    #
    # pkg/controller/volume
    # pkg/kubelet/volumemanager
    # pkg/volume
    # pkg/util/mount
    # test/e2e/storage
    # test/e2e/testing-manifests/storage-csi
    run_if_changed: '^(pkg\/controller\/volume|pkg\/kubelet\/volumemanager|pkg\/volume|pkg\/util\/mount|test\/e2e\/storage|test\/e2e\/testing-manifests\/storage-csi)'
    branches:
    # TODO(releng): Remove once repo default branch has been renamed
    - master
    - main
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-dind-enabled: "true"
      preset-pull-kubernetes-e2e: "true"
      preset-pull-kubernetes-e2e-gce: "true"
    decorate: true
    decoration_config:
      timeout: 170m
    path_alias: k8s.io/kubernetes
    extra_refs:
    - org: kubernetes
      repo: release
      base_ref: master
      path_alias: k8s.io/release
    spec:
      containers:
      - command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --build=quick
        - --cluster=
        - --extract=local
        - --gcp-node-image=gci
        - --gcp-zone=us-west1-b
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-csi-serial
        - --test_args=--ginkgo.focus=CSI.*(\[Serial\]|\[Disruptive\]) --ginkgo.skip=\[Flaky\]|\[Feature:.+\]|\[Slow\] --minStartupPods=8
        - --timeout=150m
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240311-b09cdeb92c-master
        resources:
          limits:
            cpu: "4"
            memory: "6Gi"
          requests:
            cpu: "4"
            memory: "6Gi"
        securityContext:
          privileged: true
    annotations:
      testgrid-create-test-group: 'true'
  - name: pull-kubernetes-e2e-gce-storage-disruptive
    cluster: k8s-infra-prow-build
    always_run: false
    optional: true
    branches:
    # TODO(releng): Remove once repo default branch has been renamed
    - master
    - main
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-dind-enabled: "true"
      preset-pull-kubernetes-e2e: "true"
      preset-pull-kubernetes-e2e-gce: "true"
    decorate: true
    decoration_config:
      timeout: 300m
    path_alias: k8s.io/kubernetes
    extra_refs:
    - org: kubernetes
      repo: release
      base_ref: master
      path_alias: k8s.io/release
    spec:
      containers:
      - command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --build=quick
        - --extract=local
        - --gcp-master-image=gci
        - --gcp-node-image=gci
        - --gcp-zone=us-west1-b
        - --provider=gce
        - --test_args=--ginkgo.focus=\[sig-storage\].*\[Disruptive\] --ginkgo.skip=\[Driver:.gcepd\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
        - --timeout=240m
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240311-b09cdeb92c-master
        resources:
          limits:
            cpu: "4"
            memory: "6Gi"
          requests:
            cpu: "4"
            memory: "6Gi"
        securityContext:
          privileged: true
    annotations:
      testgrid-create-test-group: 'true'
periodics:
- interval: 24h
  name: ci-kubernetes-e2e-gce-iscsi-serial
  cluster: k8s-infra-prow-build
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  decorate: true
  decoration_config:
    timeout: 150m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --check-leaked-resources
      - --env=KUBE_UBUNTU_INSTALL_CONTAINERD_VERSION=v1.7.14
      - --env=KUBE_UBUNTU_INSTALL_RUNC_VERSION=v1.1.12
      - --env=LOG_DUMP_SYSTEMD_SERVICES=containerd
      - --env=CONTAINER_RUNTIME_TEST_HANDLER=true
      - --env=KUBE_MASTER_OS_DISTRIBUTION=ubuntu
      - --env=KUBE_GCE_MASTER_IMAGE=ubuntu-2204-jammy-v20220712a
      - --env=KUBE_GCE_MASTER_PROJECT=ubuntu-os-cloud
      - --env=KUBE_NODE_OS_DISTRIBUTION=ubuntu
      - --env=KUBE_GCE_NODE_IMAGE=ubuntu-2204-jammy-v20220712a
      - --env=KUBE_GCE_NODE_PROJECT=ubuntu-os-cloud
      - --extract=ci/fast/latest-fast
      - --extract-ci-bucket=k8s-release-dev
      - --gcp-master-image=ubuntu
      - --gcp-node-image=ubuntu
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Driver:.iscsi\] --ginkgo.skip=\[Flaky\] --minStartupPods=8
      - --timeout=120m
      resources:
        requests:
          memory: "2000Mi"
          cpu: 4000m
        limits:
          memory: "2000Mi"
          cpu: 4000m
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240311-b09cdeb92c-master
  annotations:
    testgrid-num-columns-recent: '20'
- interval: 24h
  name: ci-kubernetes-e2e-snapshot
  cluster: k8s-infra-prow-build
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  decorate: true
  decoration_config:
    timeout: 150m
  spec:
    containers:
    - command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      args:
      - --check-leaked-resources
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:VolumeSnapshotDataSource\] --ginkgo.skip=\[Disruptive\]|\[Flaky\] --minStartupPods=8
      - --timeout=120m
      resources:
        requests:
          memory: "2000Mi"
          cpu: 4000m
        limits:
          memory: "2000Mi"
          cpu: 4000m
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240311-b09cdeb92c-master
  annotations:
    testgrid-num-columns-recent: '20'
    testgrid-num-failures-to-alert: '6'
    testgrid-alert-email: kubernetes-sig-storage-test-failures@googlegroups.com
