presubmits:
  kubernetes-sigs/hierarchical-namespaces:
  - name: pull-hnc-test
    annotations:
      testgrid-dashboards: wg-multi-tenancy-hnc
      testgrid-tab-name: presubmit-tests
    decorate: true
    path_alias: sigs.k8s.io/hierarchical-namespaces
    run_if_changed: ".*"
    spec:
      containers:
      - image: public.ecr.aws/docker/library/golang:1.20
        command:
        - ./hack/ci-test.sh
