presubmits:
    kubernetes-sigs/multi-tenancy:
    - name: pull-mtb-test
      annotations:
        testgrid-dashboards: wg-multi-tenancy-mtb
        testgrid-tab-name: presubmit-tests
      decorate: true
      labels:
        preset-kind-volume-mounts: "true"
        preset-dind-enabled: "true"
      path_alias: sigs.k8s.io/multi-tenancy
      run_if_changed: "benchmarks/kubectl-mtb/.*"
      spec:
        containers:
        - image: gcr.io/k8s-staging-test-infra/krte:v20230703-e6ae5b372a-master
          command:
            - wrapper.sh
            - ./benchmarks/kubectl-mtb/hack/ci-test.sh
          securityContext:
            privileged: true
