steps:
  - name: gcr.io/cloud-builders/docker
    args:
    - build
    - -t
    - gcr.io/$PROJECT_ID/gcloud-terraform:$_GIT_TAG
    - --build-arg=IMAGE_ARG=gcr.io/$PROJECT_ID/gcloud-terraform:$_GIT_TAG
    - .
    dir: images/gcloud-terraform/
  - name: gcr.io/cloud-builders/docker
    args:
    - tag
    - gcr.io/$PROJECT_ID/gcloud-terraform:$_GIT_TAG
    - gcr.io/$PROJECT_ID/gcloud-terraform:latest
substitutions:
  _GIT_TAG: '12345'
images:
  - 'gcr.io/$PROJECT_ID/gcloud-terraform:$_GIT_TAG'
  - 'gcr.io/$PROJECT_ID/gcloud-terraform:latest'
