periodics:
- interval: 3h
  cluster: eks-prow-build-cluster
  name: apisnoop-conformance-gate
  annotations:
    testgrid-dashboards: sig-arch-conformance
    testgrid-tab-name: apisnoop-conformance-gate
    test-grid-alert-email: kubernetes-sig-arch-conformance-test-failures@googlegroups.com
    testgrid-num-failures-to-alert: '1'
    description: 'Uses APISnoop to check that new GA endpoints are conformance tested in latest e2e test run'
  decorate: true
  spec:
    containers:
    - name: apisnoop-gate
      image: gcr.io/k8s-staging-apisnoop/snoopdb:v20240310-auditlogger-1.2.11-30-g3c40359
      env:
        - name: LOAD_K8S_DATA
          value: "true"
      command:
      - /usr/local/bin/docker-entrypoint.sh
      - postgres
      resources:
        requests:
          memory: 4Gi
          cpu: 2
        limits:
          memory: 4Gi
          cpu: 2
