periodics:
- name: maintenance-ci-shared-aws-janitor
  cluster: eks-prow-build-cluster
  interval: 1h
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential-aws-shared-testing: "true"
  decorate: true
  spec:
    containers:
    - command:
      - /app
      args:
      - --ttl=6h
      - --path=s3://cloud-provider-aws-shared-e2e/objs.json
      - --exclude-tags=Shared=Ignore
      image: gcr.io/k8s-staging-boskos/aws-janitor:v20230908-da54d76
      resources:
        requests:
          cpu: 1
          memory: "2Gi"
        limits:
          cpu: 1
          memory: "2Gi"
  annotations:
    testgrid-dashboards: sig-testing-maintenance
    testgrid-tab-name: ci-shared-aws-janitor
    description: Deletes old AWS resources for shared jobs

- interval: 1h
  name: maintenance-ci-aws-janitor
  labels:
    preset-service-account: "true"
    preset-aws-ssh: "true"
    preset-aws-credential: "true"
  decorate: true
  spec:
    containers:
    - command:
      - /app
      args:
      - --ttl=2h30m
      - --path=s3://k8s-kops-prow/objs.json
      - --exclude-tags=Shared=Ignore
      image: gcr.io/k8s-staging-boskos/aws-janitor:v20230908-da54d76
  annotations:
    testgrid-dashboards: sig-testing-maintenance
    testgrid-tab-name: ci-aws-janitor
    description: Deletes old AWS resources

- interval: 24h
  name: maintenance-ci-janitor
  labels:
    preset-service-account: "true"
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
    path_alias: k8s.io/test-infra
  spec:
    containers:
    - command:
      - runner.sh
      args:
      - go
      - run
      - experiment/ci-janitor/main.go
      - --config-path=config/prow/config.yaml
      - --job-config-path=config/jobs
      - --janitor-path=boskos/cmd/janitor/gcp_janitor.py
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-master
      resources:
        requests:
          cpu: 5
          memory: "8Gi"
  annotations:
    testgrid-dashboards: sig-testing-maintenance
    testgrid-tab-name: ci-janitor
    description: Deletes old GCP resources from periodic jobs

- interval: 1h
  name: maintenance-pull-janitor
  labels:
    preset-service-account: "true"
  decorate: true
  decoration_config:
    timeout: 30m
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
    path_alias: k8s.io/test-infra
    workdir: true
  spec:
    containers:
    - command:
      - runner.sh
      - /home/prow/go/src/k8s.io/test-infra/scenarios/kubernetes_janitor.py
      args:
      - --mode=pr
      env:
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231206-f7b83ffbe6-experimental
      resources:
        requests:
          cpu: 5
          memory: "8Gi"
  annotations:
    testgrid-dashboards: sig-testing-maintenance
    testgrid-tab-name: pull-janitor
    description: Deletes old GCP resources from presubmit jobs
