periodics:
- name: ci-test-infra-continuous-test
  cluster: k8s-infra-prow-build
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  interval: 1h
  labels:
    # Enable dind for linters that required docker to run, for example typescript.
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240405-68dde9badf-test-infra
      command:
      - runner.sh
      args:
      - make
      - test
      - verify
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 2
          memory: 4Gi
  annotations:
    testgrid-dashboards: sig-testing-misc
    testgrid-tab-name: continuous
    testgrid-broken-column-threshold: '0.5'
    description: Runs `make test verify` on the test-infra repo every hour

- name: metrics-kettle
  interval: 1h
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  spec:
    serviceAccountName: triage
    containers:
    - image: gcr.io/k8s-staging-test-infra/bigquery:v20240205-69ac5748ba
      args:
      - ./kettle/monitor.py
      - --stale=6
      - --table
      - k8s-gubernator:build.all
      - k8s-gubernator:build.week
      - k8s-gubernator:build.day
  annotations:
    testgrid-num-failures-to-alert: '6'
    testgrid-alert-stale-results-hours: '12'
    testgrid-dashboards: sig-testing-misc
    testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-oncall@google.com
    testgrid-broken-column-threshold: '0.5'
    description: Monitors Kettle's BigQuery database freshness.

- name: job-migration-todo-report
  decorate: true
  interval: 24h
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  spec:
    containers:
    - image: gcr.io/k8s-staging-infra-tools/k8s-infra:latest
      command:
      - hack/cluster-migration/update_todo.sh
  annotations:
    testgrid-dashboards: sig-testing-misc
    testgrid-tab-name: job-migration-todo-report
    description: Reports the status of the job migration to Prow
