images:
  cos-stable1:
    image_family: cos-stable
    project: cos-cloud
    machine: n1-standard-2 # These tests need a lot of memory
    metadata: "user-data</workspace/test-infra/jobs/e2e_node/containerd/init-eviction.yaml,cni-template</workspace/test-infra/jobs/e2e_node/containerd/cni.template,containerd-config</workspace/test-infra/jobs/e2e_node/containerd/config-systemd.toml"
