---
gitHubLogin: "k8s-infra-ci-robot"
gitHubToken: "/etc/github-token/token"
gitName: "Kubernetes Prow Robot"
gitEmail: "75457971+k8s-infra-ci-robot@users.noreply.github.com"
onCallAddress: "https://storage.googleapis.com/kubernetes-jenkins/oncall.json"
skipPullRequest: false
gitHubOrg: "kubernetes"
gitHubRepo: "test-infra"
remoteName: "test-infra"
headBranchName: "prowjobs-autobump"
upstreamURLBase: "https://raw.githubusercontent.com/kubernetes/test-infra/master"
includedConfigPaths:
  - "config/jobs"
extraFiles:
  - "config/jobs/image-pushing/k8s-staging-e2e-test-images.sh"
  - "config/jobs/image-pushing/k8s-staging-sig-storage.sh"
  - "config/jobs/kubernetes/sig-cloud-provider/azure/generate.sh"
  - "config/jobs/kubernetes/kops/build_jobs.py"
  - "config/jobs/kubernetes-csi/gen-jobs.sh"
  - "config/jobs/README.md"
  - "releng/generate_tests.py"
  - "releng/test_config.yaml"
  - "images/kubekins-e2e/Dockerfile"
targetVersion: "latest"
prefixes:
  - name: "k8s-testimages images"
    prefix: "gcr.io/k8s-testimages/"
    repo: "https://github.com/kubernetes/test-infra"
    summarise: false
    consistentImages: false
  - name: "k8s-staging-test-infra GCR images"
    prefix: "gcr.io/k8s-staging-test-infra"
    repo: "https://github.com/kubernetes/test-infra"
    summarise: false
    consistentImages: false
  - name: "k8s-staging-test-infra AR images"
    prefix: "us-central1-docker.pkg.dev/k8s-staging-test-infra/images"
    repo: "https://github.com/kubernetes/test-infra"
    summarise: false
    consistentImages: false
